// Code generated by gmicompile - DO NOT EDIT.

package axisui

import (
	"encoding/json"
	"syscall"
	"unsafe"

	"github.com/sittner/linuxcnc/src/gomc/internal/apiserver"
)

var _ = json.Marshal
var _ = syscall.EINVAL
var _ unsafe.Pointer

// --- Types ---

type JogInputs struct {
	Disable bool `json:"disable"`
	XPlus bool `json:"x_plus"`
	XMinus bool `json:"x_minus"`
	YPlus bool `json:"y_plus"`
	YMinus bool `json:"y_minus"`
	ZPlus bool `json:"z_plus"`
	ZMinus bool `json:"z_minus"`
	APlus bool `json:"a_plus"`
	AMinus bool `json:"a_minus"`
	BPlus bool `json:"b_plus"`
	BMinus bool `json:"b_minus"`
	CPlus bool `json:"c_plus"`
	CMinus bool `json:"c_minus"`
	UPlus bool `json:"u_plus"`
	UMinus bool `json:"u_minus"`
	VPlus bool `json:"v_plus"`
	VMinus bool `json:"v_minus"`
	WPlus bool `json:"w_plus"`
	WMinus bool `json:"w_minus"`
}

type SliderInputs struct {
	Scale float64 `json:"scale"`
	ScaleAbs float64 `json:"scale_abs"`
	Feedoverride int32 `json:"feedoverride"`
	FeedoverrideAbs int32 `json:"feedoverride_abs"`
	Rapidoverride int32 `json:"rapidoverride"`
	RapidoverrideAbs int32 `json:"rapidoverride_abs"`
	Spinoverride int32 `json:"spinoverride"`
	SpinoverrideAbs int32 `json:"spinoverride_abs"`
	Jogspeed int32 `json:"jogspeed"`
	JogspeedAbs int32 `json:"jogspeed_abs"`
	Ajogspeed int32 `json:"ajogspeed"`
	AjogspeedAbs int32 `json:"ajogspeed_abs"`
	Maxvel int32 `json:"maxvel"`
	MaxvelAbs int32 `json:"maxvel_abs"`
}

type NotificationInputs struct {
	NotificationsClear bool `json:"notifications_clear"`
	NotificationsClearInfo bool `json:"notifications_clear_info"`
	NotificationsClearError bool `json:"notifications_clear_error"`
	ResumeInhibit bool `json:"resume_inhibit"`
}

// --- Callbacks Interface ---

// AxisuiCallbacks defines the API methods that modules must implement.
type AxisuiCallbacks interface {
	GetJogInputs() (*JogInputs, error)
	GetSliderInputs() (*SliderInputs, error)
	GetNotificationInputs() (*NotificationInputs, error)
	SetJogAxis(axis string) (bool, error)
	SetJogIncrement(increment float64) (bool, error)
	SetIsRunning(running bool) (bool, error)
	SetHasNotifications(has bool) (bool, error)
	SetError(error bool) (bool, error)
	SetAbort(abort bool) (bool, error)
}

// --- Dispatch Functions ---

func axisuiDispatchGetJogInputs(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	result, err := impl.GetJogInputs()
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchGetSliderInputs(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	result, err := impl.GetSliderInputs()
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchGetNotificationInputs(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	result, err := impl.GetNotificationInputs()
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetJogAxis(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Axis string `json:"axis"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetJogAxis(params.Axis)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetJogIncrement(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Increment float64 `json:"increment"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetJogIncrement(params.Increment)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetIsRunning(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Running bool `json:"running"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetIsRunning(params.Running)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetHasNotifications(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Has bool `json:"has"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetHasNotifications(params.Has)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetError(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Error bool `json:"error"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetError(params.Error)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

func axisuiDispatchSetAbort(callbacks unsafe.Pointer, req []byte) ([]byte, error) {
	impl := *(*AxisuiCallbacks)(callbacks)
	var params struct {
		Abort bool `json:"abort"`
	}
	if len(req) > 0 {
		if err := json.Unmarshal(req, &params); err != nil {
			return nil, syscall.EINVAL
		}
	}
	result, err := impl.SetAbort(params.Abort)
	if err != nil {
		return nil, err
	}
	return json.Marshal(result)
}

// --- API Metadata ---

var AxisuiMeta = &apiserver.APIMeta{
	Name:       "axisui",
	Version:    1,
	RESTExport: true,
	Prefix:     "axisui",
	Funcs: []apiserver.FuncMeta{
		{
			Name:     "get_jog_inputs",
			Method:   "GET",
			Path:     "/jog-inputs",
			RTSafe:   false,
			Dispatch: axisuiDispatchGetJogInputs,
		},
		{
			Name:     "get_slider_inputs",
			Method:   "GET",
			Path:     "/slider-inputs",
			RTSafe:   false,
			Dispatch: axisuiDispatchGetSliderInputs,
		},
		{
			Name:     "get_notification_inputs",
			Method:   "GET",
			Path:     "/notification-inputs",
			RTSafe:   false,
			Dispatch: axisuiDispatchGetNotificationInputs,
		},
		{
			Name:     "set_jog_axis",
			Method:   "POST",
			Path:     "/set-jog-axis",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetJogAxis,
		},
		{
			Name:     "set_jog_increment",
			Method:   "POST",
			Path:     "/set-jog-increment",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetJogIncrement,
		},
		{
			Name:     "set_is_running",
			Method:   "POST",
			Path:     "/set-is-running",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetIsRunning,
		},
		{
			Name:     "set_has_notifications",
			Method:   "POST",
			Path:     "/set-has-notifications",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetHasNotifications,
		},
		{
			Name:     "set_error",
			Method:   "POST",
			Path:     "/set-error",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetError,
		},
		{
			Name:     "set_abort",
			Method:   "POST",
			Path:     "/set-abort",
			RTSafe:   false,
			Dispatch: axisuiDispatchSetAbort,
		},
	},
}

// --- Registration ---

// RegisterAxisuiAPI registers an implementation of the axisui API.
func RegisterAxisuiAPI(registry *apiserver.Registry, instance string, impl AxisuiCallbacks) error {
	cb := impl
	return registry.Register("axisui", 1, instance, unsafe.Pointer(&cb))
}
