// Package pkgreg manages the packages.conf registry and generates derived
// files (imports_generated.go, go.work) for the gomc-server binary.
package pkgreg

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// EntryType identifies the kind of package in the registry.
type EntryType string

const (
	TypeGMI   EntryType = "gmi"
	TypeGomod EntryType = "gomod"
)

// Entry is one line in packages.conf.
type Entry struct {
	Type       EntryType // "gmi" or "gomod"
	ImportPath string    // relative import path (e.g. "generated/gmi/kins" or "internal/adsmodule")
	UseDir     string    // (optional) absolute dir for go.work "use" (external packages only)
}

// Registry holds the parsed contents of packages.conf.
type Registry struct {
	Entries []Entry
}

// GoModule is the Go module path for the launcher.
const GoModule = "github.com/sittner/linuxcnc/src/launcher"

// ReadFile parses a packages.conf file.
func ReadFile(path string) (*Registry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var reg Registry
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		e := Entry{
			Type:       EntryType(fields[0]),
			ImportPath: fields[1],
		}
		if len(fields) >= 3 {
			e.UseDir = fields[2]
		}
		reg.Entries = append(reg.Entries, e)
	}
	return &reg, scanner.Err()
}

// WriteFile writes the registry back to packages.conf.
func (r *Registry) WriteFile(path string) error {
	var buf strings.Builder
	buf.WriteString("# packages.conf — managed by modcompile. DO NOT EDIT MANUALLY.\n")
	buf.WriteString("#\n")
	buf.WriteString("# Format: TYPE IMPORT_PATH [USE_DIR]\n")
	buf.WriteString("#\n")
	buf.WriteString("# TYPE:\n")
	buf.WriteString("#   gmi     — generated GMI dispatch package (compiled into gomc-server)\n")
	buf.WriteString("#   gomod   — Go module compiled into gomc-server\n")
	buf.WriteString("#\n")
	buf.WriteString("# IMPORT_PATH — Go import path for the blank import in imports_generated.go\n")
	buf.WriteString("# USE_DIR     — (optional) directory for go.work \"use\" directive (external packages only)\n\n")

	// Group by type.
	gmi := r.entriesByType(TypeGMI)
	gomod := r.entriesByType(TypeGomod)

	if len(gmi) > 0 {
		buf.WriteString("# Core GMI dispatch (generated, part of this module)\n")
		for _, e := range gmi {
			buf.WriteString(fmt.Sprintf("gmi %s\n", e.ImportPath))
		}
		buf.WriteString("\n")
	}

	if len(gomod) > 0 {
		buf.WriteString("# Go modules\n")
		for _, e := range gomod {
			if e.UseDir != "" {
				buf.WriteString(fmt.Sprintf("gomod %s %s\n", e.ImportPath, e.UseDir))
			} else {
				buf.WriteString(fmt.Sprintf("gomod %s\n", e.ImportPath))
			}
		}
		buf.WriteString("\n")
	}

	return os.WriteFile(path, []byte(buf.String()), 0644)
}

func (r *Registry) entriesByType(t EntryType) []Entry {
	var out []Entry
	for _, e := range r.Entries {
		if e.Type == t {
			out = append(out, e)
		}
	}
	return out
}

// Add adds a new entry to the registry. Returns false if already present.
func (r *Registry) Add(e Entry) bool {
	for _, existing := range r.Entries {
		if existing.Type == e.Type && existing.ImportPath == e.ImportPath {
			return false
		}
	}
	r.Entries = append(r.Entries, e)
	return true
}

// Remove removes an entry by import path. Returns false if not found.
func (r *Registry) Remove(importPath string) bool {
	for i, e := range r.Entries {
		if e.ImportPath == importPath {
			r.Entries = append(r.Entries[:i], r.Entries[i+1:]...)
			return true
		}
	}
	return false
}

// GenerateImports generates cmd/gomc-server/imports_generated.go from the registry.
func (r *Registry) GenerateImports(serverDir string) error {
	path := filepath.Join(serverDir, "cmd", "gomc-server", "imports_generated.go")

	var buf strings.Builder
	buf.WriteString("// Code generated by modcompile. DO NOT EDIT.\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("import (\n")

	gmi := r.entriesByType(TypeGMI)
	gomod := r.entriesByType(TypeGomod)

	if len(gmi) > 0 {
		buf.WriteString("\t// GMI dispatch packages\n")
		for _, e := range gmi {
			buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
		}
	}

	if len(gomod) > 0 {
		if len(gmi) > 0 {
			buf.WriteString("\n")
		}
		buf.WriteString("\t// Go modules\n")
		for _, e := range gomod {
			buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
		}
	}

	buf.WriteString(")\n")

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(buf.String()), 0644)
}

// GenerateGoWork generates go.work from the registry. Only external packages
// (with UseDir set) get "use" directives. If no external packages exist,
// go.work is removed (not needed for pure in-module builds).
func (r *Registry) GenerateGoWork(serverDir string) error {
	path := filepath.Join(serverDir, "go.work")

	var useDirs []string
	for _, e := range r.Entries {
		if e.UseDir != "" {
			useDirs = append(useDirs, e.UseDir)
		}
	}

	if len(useDirs) == 0 {
		// No external packages — remove go.work if it exists.
		err := os.Remove(path)
		if os.IsNotExist(err) {
			return nil
		}
		// Also remove go.work.sum if it exists.
		os.Remove(path + ".sum")
		return err
	}

	sort.Strings(useDirs)

	var buf strings.Builder
	buf.WriteString("// Code generated by modcompile. DO NOT EDIT.\n")
	buf.WriteString("go 1.22\n\n")
	buf.WriteString("use (\n")
	buf.WriteString("\t.\n")
	for _, d := range useDirs {
		buf.WriteString(fmt.Sprintf("\t%s\n", d))
	}
	buf.WriteString(")\n")

	return os.WriteFile(path, []byte(buf.String()), 0644)
}
