package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/launcher/internal/gmicompile/ast"
)

// GenerateClientHeader writes C client header (client struct, function declarations).
func GenerateClientHeader(w io.Writer, api *ast.API) error {
	g := &clientHeaderGen{w: w, api: api}
	return g.generate()
}

// GenerateClientSource writes C client implementation (cJSON/libcurl).
func GenerateClientSource(w io.Writer, api *ast.API) error {
	g := &clientSourceGen{w: w, api: api}
	return g.generate()
}

// ---------------------------------------------------------------------------
// Client Header Generator
// ---------------------------------------------------------------------------

type clientHeaderGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *clientHeaderGen) generate() error {
	g.emitHeaderGuard()
	g.emitIncludes()
	g.emitForwardDecls()
	g.emitClientFunctions()
	g.emitHeaderGuardEnd()
	return g.err
}

func (g *clientHeaderGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientHeaderGen) emitHeaderGuard() {
	guard := strings.ToUpper(g.api.Name) + "_CLIENT_H"
	g.printf("// Generated by gmicompile - DO NOT EDIT\n")
	g.printf("#ifndef %s\n", guard)
	g.printf("#define %s\n\n", guard)
}

func (g *clientHeaderGen) emitHeaderGuardEnd() {
	guard := strings.ToUpper(g.api.Name) + "_CLIENT_H"
	g.printf("#endif // %s\n", guard)
}

func (g *clientHeaderGen) emitIncludes() {
	// Include the server header for type definitions
	g.printf("#include \"%s_api.h\"\n\n", g.api.Name)
	g.printf("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
}

func (g *clientHeaderGen) emitForwardDecls() {
	g.printf("// ─── Client Handle ───\n\n")
	g.printf("typedef struct %s_client %s_client_t;\n\n", g.api.Name, g.api.Name)

	g.printf("// Create a new client connected to the given base URL.\n")
	g.printf("// Example: %s_client_new(\"http://localhost:8080/api/v1/%s\")\n", g.api.Name, g.api.Prefix)
	g.printf("%s_client_t *%s_client_new(const char *base_url);\n\n", g.api.Name, g.api.Name)

	g.printf("// Free the client and release resources.\n")
	g.printf("void %s_client_free(%s_client_t *client);\n\n", g.api.Name, g.api.Name)
}

func (g *clientHeaderGen) emitClientFunctions() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// ─── Client Functions ───\n\n")
	for _, fn := range g.api.Funcs {
		g.emitClientFunctionDecl(fn)
	}
	g.printf("#ifdef __cplusplus\n}\n#endif\n\n")
}

func (g *clientHeaderGen) emitClientFunctionDecl(fn ast.Func) {
	g.printf("// %s %s\n", fn.Method, fn.Path)
	if fn.Doc != "" {
		g.printf("// %s\n", fn.Doc)
	}
	g.printf("int %s_client_%s(\n", g.api.Name, toSnakeCase(fn.Name))
	g.printf("    %s_client_t *client", g.api.Name)

	// Parameters
	for _, p := range fn.Params {
		cType := g.toCType(p.Type)
		if p.Type.Kind == ast.TypeNamed {
			g.printf(",\n    const %s *%s", cType, toSnakeCase(p.Name))
		} else {
			g.printf(",\n    %s %s", cType, toSnakeCase(p.Name))
		}
	}

	// Return value as out parameter
	if fn.Return != nil {
		retType := g.toCType(*fn.Return)
		if fn.Return.Kind == ast.TypeSlice {
			g.printf(",\n    %s **out", retType)
			g.printf(",\n    size_t *out_len")
		} else {
			g.printf(",\n    %s *out", retType)
		}
	}

	g.printf("\n);\n\n")
}

func (g *clientHeaderGen) toCType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", g.api.Name, toSnakeCase(t.Name))
	case ast.TypeSlice:
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s[%d]", elemType, t.ArrayLen)
	}
	return "void"
}

// ---------------------------------------------------------------------------
// Client Source Generator
// ---------------------------------------------------------------------------

type clientSourceGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *clientSourceGen) generate() error {
	g.emitIncludes()
	g.emitClientStruct()
	g.emitHelpers()
	g.emitNewFree()
	g.emitClientFunctions()
	return g.err
}

func (g *clientSourceGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientSourceGen) emitIncludes() {
	g.printf("// Generated by gmicompile - DO NOT EDIT\n\n")
	g.printf("#include \"%s_client.h\"\n", g.api.Name)
	g.printf("#include <gmi.h>\n")
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n\n")
}

func (g *clientSourceGen) emitClientStruct() {
	g.printf("// ─── Client Struct ───\n\n")
	g.printf("struct %s_client {\n", g.api.Name)
	g.printf("    gmi_http_t *http;\n")
	g.printf("};\n\n")
}

func (g *clientSourceGen) emitHelpers() {
	// No inline helpers needed - libgmi provides all utilities
}

func (g *clientSourceGen) emitNewFree() {
	name := g.api.Name

	g.printf("// ─── Constructor / Destructor ───\n\n")
	g.printf("%s_client_t *%s_client_new(const char *base_url) {\n", name, name)
	g.printf("    %s_client_t *c = calloc(1, sizeof(*c));\n", name)
	g.printf("    if (!c) return NULL;\n")
	g.printf("    c->http = gmi_http_new(base_url);\n")
	g.printf("    if (!c->http) {\n")
	g.printf("        free(c);\n")
	g.printf("        return NULL;\n")
	g.printf("    }\n")
	g.printf("    return c;\n")
	g.printf("}\n\n")

	g.printf("void %s_client_free(%s_client_t *c) {\n", name, name)
	g.printf("    if (!c) return;\n")
	g.printf("    gmi_http_free(c->http);\n")
	g.printf("    free(c);\n")
	g.printf("}\n\n")
}

func (g *clientSourceGen) emitClientFunctions() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// ─── Client Functions ───\n\n")
	for _, fn := range g.api.Funcs {
		g.emitClientFunction(fn)
	}
}

func (g *clientSourceGen) emitClientFunction(fn ast.Func) {
	name := g.api.Name
	fnName := toSnakeCase(fn.Name)

	// Function signature
	g.printf("int %s_client_%s(\n", name, fnName)
	g.printf("    %s_client_t *c", name)

	for _, p := range fn.Params {
		cType := g.toCType(p.Type)
		if p.Type.Kind == ast.TypeNamed {
			g.printf(",\n    const %s *%s", cType, toSnakeCase(p.Name))
		} else {
			g.printf(",\n    %s %s", cType, toSnakeCase(p.Name))
		}
	}

	if fn.Return != nil {
		retType := g.toCType(*fn.Return)
		if fn.Return.Kind == ast.TypeSlice {
			g.printf(",\n    %s **out", retType)
			g.printf(",\n    size_t *out_len")
		} else {
			g.printf(",\n    %s *out", retType)
		}
	}
	g.printf("\n) {\n")

	// Determine HTTP method enum
	methodEnum := "GMI_HTTP_GET"
	switch fn.Method {
	case "POST":
		methodEnum = "GMI_HTTP_POST"
	case "PUT":
		methodEnum = "GMI_HTTP_PUT"
	case "PATCH":
		methodEnum = "GMI_HTTP_PATCH"
	case "DELETE":
		methodEnum = "GMI_HTTP_DELETE"
	}

	// Create request
	g.printf("    gmi_request_t *req = gmi_request_new(c->http, %s, \"%s\");\n", methodEnum, fn.Path)
	g.printf("    if (!req) return GMI_ERR_ALLOC;\n\n")

	// Handle path parameters
	g.emitPathParams(fn)

	// Handle request body for POST/PUT/PATCH
	if fn.Method == "POST" || fn.Method == "PUT" || fn.Method == "PATCH" {
		g.emitRequestBody(fn)
	}

	// Execute request
	g.printf("    int rc = gmi_request_execute(req);\n")
	g.printf("    if (rc != GMI_OK) {\n")
	g.printf("        gmi_request_free(req);\n")
	g.printf("        return rc;\n")
	g.printf("    }\n\n")

	// Parse response
	if fn.Return != nil {
		g.emitResponseParsing(fn)
	}

	g.printf("    gmi_request_free(req);\n")
	g.printf("    return GMI_OK;\n")
	g.printf("}\n\n")
}

func (g *clientSourceGen) emitPathParams(fn ast.Func) {
	// Check for path parameters in the path like {name}
	if !strings.Contains(fn.Path, "{") {
		return
	}

	// For each param that might be a path param, check if it appears in the path
	for _, p := range fn.Params {
		paramPlaceholder := "{" + p.Name + "}"
		if strings.Contains(fn.Path, paramPlaceholder) {
			pname := toSnakeCase(p.Name)
			if p.Type.Kind == ast.TypePrimitive && p.Type.Name == "string" {
				g.printf("    gmi_request_path_param(req, \"%s\", %s);\n", p.Name, pname)
			}
		}
	}
	g.printf("\n")
}

func (g *clientSourceGen) emitRequestBody(fn ast.Func) {
	// Filter out path parameters (they're already in the URL)
	bodyParams := []ast.Param{}
	for _, p := range fn.Params {
		paramPlaceholder := "{" + p.Name + "}"
		if !strings.Contains(fn.Path, paramPlaceholder) {
			bodyParams = append(bodyParams, p)
		}
	}

	if len(bodyParams) == 0 {
		return
	}

	// Build JSON request body
	g.printf("    cJSON *body = gmi_json_object();\n")
	for _, p := range bodyParams {
		pname := toSnakeCase(p.Name)
		switch {
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "string":
			g.printf("    if (%s) gmi_json_add_str(body, \"%s\", %s);\n", pname, p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "bool":
			g.printf("    gmi_json_add_bool(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "i32":
			g.printf("    gmi_json_add_i32(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "i64":
			g.printf("    gmi_json_add_i64(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "u32":
			g.printf("    gmi_json_add_u32(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "u64":
			g.printf("    gmi_json_add_u64(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypePrimitive && p.Type.Name == "f64":
			g.printf("    gmi_json_add_f64(body, \"%s\", %s);\n", p.Name, pname)
		case p.Type.Kind == ast.TypeNamed:
			g.printf("    // TODO: serialize struct %s to body\n", pname)
		}
	}
	g.printf("    gmi_request_set_json(req, body);\n")
	g.printf("    cJSON_Delete(body);\n\n")
}

func (g *clientSourceGen) emitResponseParsing(fn ast.Func) {
	g.printf("    if (out) {\n")
	g.printf("        cJSON *json = gmi_request_response_json(req);\n")
	g.printf("        if (json) {\n")

	ret := fn.Return
	switch {
	case ret.Kind == ast.TypePrimitive && ret.Name == "bool":
		g.printf("            *out = cJSON_IsTrue(json);\n")
	case ret.Kind == ast.TypePrimitive && (ret.Name == "i32" || ret.Name == "i64" || ret.Name == "u32" || ret.Name == "u64"):
		g.printf("            *out = (%s)cJSON_GetNumberValue(json);\n", g.toCType(*ret))
	case ret.Kind == ast.TypePrimitive && ret.Name == "f64":
		g.printf("            *out = cJSON_GetNumberValue(json);\n")
	case ret.Kind == ast.TypePrimitive && ret.Name == "string":
		g.printf("            const char *s = cJSON_GetStringValue(json);\n")
		g.printf("            *out = s ? strdup(s) : NULL;\n")
	case ret.Kind == ast.TypeNamed:
		g.emitStructParsing(fn, *ret)
	case ret.Kind == ast.TypeSlice:
		g.emitSliceParsing(fn, *ret)
	}

	g.printf("            cJSON_Delete(json);\n")
	g.printf("        }\n")
	g.printf("    }\n\n")
}

func (g *clientSourceGen) emitStructParsing(fn ast.Func, ret ast.TypeRef) {
	// Find the type definition
	var typeDef *ast.Type
	for i := range g.api.Types {
		if g.api.Types[i].Name == ret.Name {
			typeDef = &g.api.Types[i]
			break
		}
	}
	if typeDef == nil {
		g.printf("            // TODO: parse struct %s\n", ret.Name)
		return
	}

	g.printf("            memset(out, 0, sizeof(*out));\n")
	for _, f := range typeDef.Fields {
		fname := f.Name
		cname := toSnakeCase(f.Name)
		switch {
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "string":
			g.printf("            {\n")
			g.printf("                const char *s = gmi_json_get_str(json, \"%s\");\n", fname)
			g.printf("                if (s) out->%s = strdup(s);\n", cname)
			g.printf("            }\n")
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "bool":
			g.printf("            out->%s = gmi_json_get_bool(json, \"%s\", false);\n", cname, fname)
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "i32":
			g.printf("            out->%s = gmi_json_get_i32(json, \"%s\", 0);\n", cname, fname)
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "u32":
			g.printf("            out->%s = gmi_json_get_u32(json, \"%s\", 0);\n", cname, fname)
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "i64":
			g.printf("            out->%s = gmi_json_get_i64(json, \"%s\", 0);\n", cname, fname)
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "u64":
			g.printf("            out->%s = gmi_json_get_u64(json, \"%s\", 0);\n", cname, fname)
		case f.Type.Kind == ast.TypePrimitive && f.Type.Name == "f64":
			g.printf("            out->%s = gmi_json_get_f64(json, \"%s\", 0.0);\n", cname, fname)
		default:
			g.printf("            // TODO: parse field %s\n", fname)
		}
	}
}

func (g *clientSourceGen) emitSliceParsing(fn ast.Func, ret ast.TypeRef) {
	g.printf("            if (cJSON_IsArray(json)) {\n")
	g.printf("                int n = cJSON_GetArraySize(json);\n")
	g.printf("                *out_len = (size_t)n;\n")
	elemType := g.toCType(*ret.Elem)
	g.printf("                *out = calloc(n, sizeof(%s));\n", elemType)
	g.printf("                if (*out) {\n")
	g.printf("                    cJSON *elem;\n")
	g.printf("                    int i = 0;\n")
	g.printf("                    cJSON_ArrayForEach(elem, json) {\n")
	// Generate element parsing based on element type
	if ret.Elem.Kind == ast.TypeNamed {
		g.printf("                        // TODO: parse struct element into (*out)[i]\n")
	} else {
		g.printf("                        // TODO: parse primitive element into (*out)[i]\n")
	}
	g.printf("                        i++;\n")
	g.printf("                    }\n")
	g.printf("                }\n")
	g.printf("            }\n")
}

func (g *clientSourceGen) toCType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", g.api.Name, toSnakeCase(t.Name))
	case ast.TypeSlice:
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s[%d]", elemType, t.ArrayLen)
	}
	return "void"
}
