package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/launcher/internal/gmicompile/ast"
)

// GenerateDispatchC writes a Go file with cgo that bridges C callbacks
// to the apiserver. This file:
//   - Includes the C header via cgo preamble
//   - Generates static C call wrappers for function pointers
//   - Generates Go types matching the C types
//   - Generates C→Go struct converters
//   - Generates DispatchFunc wrappers for REST
//   - Generates APIMeta with embedded dispatch
//   - Generates //export register function callable from C
func GenerateDispatchC(w io.Writer, api *ast.API, packageName, headerFile string) error {
	g := &dispatchCGen{w: w, api: api, pkg: packageName, header: headerFile}
	return g.generate()
}

type dispatchCGen struct {
	w      io.Writer
	api    *ast.API
	pkg    string
	header string // C header filename, e.g. "hal_api.h"
	err    error
}

func (g *dispatchCGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *dispatchCGen) generate() error {
	g.emitCgoPreamble()
	g.emitImports()
	g.emitConstants()
	g.emitGoTypes()
	g.emitConverters()
	g.emitGoToCConverters()
	g.emitDispatchFuncs()
	g.emitMeta()
	g.emitRegister()
	return g.err
}

// ─── cgo Preamble ───

func (g *dispatchCGen) emitCgoPreamble() {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", strings.ToUpper(g.api.Name))
	g.printf("#include \"%s\"\n", g.header)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")
	g.printf("\n")

	// Static call wrappers — cgo cannot call C function pointers directly,
	// so we generate a static wrapper for each callback.
	for _, fn := range g.api.Funcs {
		g.emitCallWrapper(fn)
	}

	g.printf("*/\n")
	g.printf("import \"C\"\n\n")
}

func (g *dispatchCGen) emitCallWrapper(fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	wrapperName := fmt.Sprintf("call_%s_%s", apiName, fnSnake)
	fnType := fmt.Sprintf("%s_%s_fn", apiName, fnSnake)

	// Build parameter list: fn pointer + same params as callback typedef
	params := []string{fmt.Sprintf("%s fn", fnType)}
	args := []string{}

	for _, p := range fn.Params {
		name := toSnakeCase(p.Name)
		params = append(params, cgoParamDecl(apiName, p))
		args = append(args, name)
		// Slice params also pass a length arg
		if p.Type.Kind == ast.TypeSlice {
			args = append(args, name+"_len")
		}
	}

	if fn.Return != nil {
		retType := toCTypeForAPI(g.api.Name, *fn.Return)
		if fn.Return.Kind == ast.TypeSlice {
			params = append(params, fmt.Sprintf("%s *out", retType))
			params = append(params, "size_t *out_len")
			args = append(args, "out", "out_len")
		} else if fn.Return.Kind == ast.TypeArray {
			elemType := toCTypeForAPI(g.api.Name, *fn.Return.Elem)
			sizeStr := cgoArraySizeStr(apiName, *fn.Return)
			params = append(params, fmt.Sprintf("%s out[%s]", elemType, sizeStr))
			args = append(args, "out")
		} else {
			params = append(params, fmt.Sprintf("%s *out", retType))
			args = append(args, "out")
		}
	}

	g.printf("static int %s(%s) {\n", wrapperName, strings.Join(params, ", "))
	g.printf("    return fn(%s);\n", strings.Join(args, ", "))
	g.printf("}\n\n")
}

// cgoParamDecl returns the C parameter declaration for use in cgo preamble wrappers.
func cgoParamDecl(apiName string, p ast.Param) string {
	name := toSnakeCase(p.Name)

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.ByRef {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("%s %s", cType, name)

	case ast.TypeNamed:
		cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
		if p.ByRef {
			return fmt.Sprintf("%s *%s", cType, name)
		}
		return fmt.Sprintf("const %s *%s", cType, name)

	case ast.TypeSlice:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		if p.ByRef {
			return fmt.Sprintf("%s *%s, size_t %s_len", elemCType, name, name)
		}
		return fmt.Sprintf("const %s *%s, size_t %s_len", elemCType, name, name)

	case ast.TypeArray:
		elemCType := toCTypeForAPI(apiName, *p.Type.Elem)
		sizeStr := cgoArraySizeStr(apiName, p.Type)
		if p.ByRef {
			return fmt.Sprintf("%s %s[%s]", elemCType, name, sizeStr)
		}
		return fmt.Sprintf("const %s %s[%s]", elemCType, name, sizeStr)
	}

	return fmt.Sprintf("void *%s", name)
}

// cgoArraySizeStr returns the C size expression for an array type (using #define name).
func cgoArraySizeStr(apiName string, t ast.TypeRef) string {
	if t.ArrayLenName != "" {
		return fmt.Sprintf("%s_%s", strings.ToUpper(apiName), t.ArrayLenName)
	}
	return fmt.Sprintf("%d", t.ArrayLen)
}

// ─── Go Imports ───

func (g *dispatchCGen) emitImports() {
	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"syscall\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/launcher/internal/apiserver\"\n")
	g.printf(")\n\n")

	// Suppress unused import warnings
	g.printf("var _ = json.Marshal\n")
	g.printf("var _ = syscall.EINVAL\n")
	g.printf("var _ unsafe.Pointer\n\n")
}

// ─── Go Constants ───

func (g *dispatchCGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// ─── Constants ───\n\n")
	g.printf("const (\n")
	for _, c := range g.api.Consts {
		g.printf("\t%s = %d\n", c.Name, c.Value)
	}
	g.printf(")\n\n")
}

// ─── Go Types (same as server_go, needed in the cgo package) ───

func (g *dispatchCGen) emitGoTypes() {
	// Enums
	if len(g.api.Enums) > 0 {
		g.printf("// ─── Enums ───\n\n")
		for _, e := range g.api.Enums {
			goName := toPascalCase(e.Name)
			g.printf("type %s int32\n\n", goName)
			g.printf("const (\n")
			for _, v := range e.Values {
				g.printf("\t%s %s = %d\n", v.Name, goName, v.Value)
			}
			g.printf(")\n\n")
		}
	}

	// Structs
	if len(g.api.Types) > 0 {
		g.printf("// ─── Types ───\n\n")
		for _, t := range g.api.Types {
			goName := toPascalCase(t.Name)
			g.printf("type %s struct {\n", goName)
			for _, f := range t.Fields {
				fieldName := toPascalCase(f.Name)
				fieldType := goTypeForDispatch(f.Type)
				jsonTag := toSnakeCase(f.Name)
				omit := ""
				if f.Type.Nullable {
					omit = ",omitempty"
				}
				g.printf("\t%s %s `json:\"%s%s\"`\n", fieldName, fieldType, jsonTag, omit)
			}
			g.printf("}\n\n")
		}
	}
}

// ─── C→Go Converters ───

func (g *dispatchCGen) emitConverters() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// ─── C→Go Converters ───\n\n")

	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
		funcName := toLowerCamelRaw(t.Name) + "CToGo"

		g.printf("func %s(src *%s) %s {\n", funcName, cType, goName)
		g.printf("\treturn %s{\n", goName)
		for _, f := range t.Fields {
			goField := toPascalCase(f.Name)
			cField := cgoFieldAccess(toSnakeCase(f.Name))
			g.emitFieldCToGo(goField, "src."+cField, f.Type)
		}
		g.printf("\t}\n")
		g.printf("}\n\n")
	}
}

func (g *dispatchCGen) emitFieldCToGo(goField, cExpr string, t ast.TypeRef) {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			if t.Nullable {
				g.printf("\t\t%s: func() string { if %s != nil { return C.GoString(%s) }; return \"\" }(),\n", goField, cExpr, cExpr)
			} else {
				g.printf("\t\t%s: C.GoString(%s),\n", goField, cExpr)
			}
		case ast.PrimBool:
			g.printf("\t\t%s: bool(%s),\n", goField, cExpr)
		case ast.PrimI32:
			if t.Nullable {
				g.printf("\t\t%s: func() *int32 { v := int32(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: int32(%s),\n", goField, cExpr)
			}
		case ast.PrimU32:
			if t.Nullable {
				g.printf("\t\t%s: func() *uint32 { v := uint32(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: uint32(%s),\n", goField, cExpr)
			}
		case ast.PrimI64:
			if t.Nullable {
				g.printf("\t\t%s: func() *int64 { v := int64(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: int64(%s),\n", goField, cExpr)
			}
		case ast.PrimU64:
			if t.Nullable {
				g.printf("\t\t%s: func() *uint64 { v := uint64(%s); return &v }(),\n", goField, cExpr)
			} else {
				g.printf("\t\t%s: uint64(%s),\n", goField, cExpr)
			}
		case ast.PrimF64:
			g.printf("\t\t%s: float64(%s),\n", goField, cExpr)
		}
	case ast.TypeNamed:
		// Could be enum or struct — for enums, cast; for structs, recurse
		goType := toPascalCase(t.Name)
		if g.isEnum(t.Name) {
			g.printf("\t\t%s: %s(%s),\n", goField, goType, cExpr)
		} else {
			converter := toLowerCamelRaw(t.Name) + "CToGo"
			if t.Nullable {
				g.printf("\t\t%s: func() *%s { v := %s(&%s); return &v }(),\n", goField, goType, converter, cExpr)
			} else {
				g.printf("\t\t%s: %s(&%s),\n", goField, converter, cExpr)
			}
		}
	case ast.TypeSlice:
		// Slice: pointer + length companion field
		// This case is handled specially in dispatch funcs, not in struct converter
		g.printf("\t\t// TODO: slice field %s\n", goField)
	case ast.TypeArray:
		g.printf("\t\t// TODO: array field %s\n", goField)
	}
}

func (g *dispatchCGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

// ─── Go→C Converters ───

func (g *dispatchCGen) emitGoToCConverters() {
	// Only emit for struct types (not enums).
	hasStructs := false
	for _, t := range g.api.Types {
		if !g.isEnum(t.Name) {
			hasStructs = true
			break
		}
	}
	if !hasStructs {
		return
	}
	g.printf("// ─── Go→C Converters ───\n\n")

	for _, t := range g.api.Types {
		goName := toPascalCase(t.Name)
		cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
		funcName := toLowerCamelRaw(t.Name) + "GoToC"

		g.printf("func %s(src %s) %s {\n", funcName, goName, cType)
		g.printf("\treturn %s{\n", cType)
		for _, f := range t.Fields {
			goField := toPascalCase(f.Name)
			cField := cgoFieldAccess(toSnakeCase(f.Name))
			g.emitFieldGoToC(cField, "src."+goField, f.Type)
		}
		g.printf("\t}\n")
		g.printf("}\n\n")
	}
}

func (g *dispatchCGen) emitFieldGoToC(cField, goExpr string, t ast.TypeRef) {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimBool:
			g.printf("\t\t%s: C.bool(%s),\n", cField, goExpr)
		case ast.PrimI32:
			g.printf("\t\t%s: C.int32_t(%s),\n", cField, goExpr)
		case ast.PrimU32:
			g.printf("\t\t%s: C.uint32_t(%s),\n", cField, goExpr)
		case ast.PrimI64:
			g.printf("\t\t%s: C.int64_t(%s),\n", cField, goExpr)
		case ast.PrimU64:
			g.printf("\t\t%s: C.uint64_t(%s),\n", cField, goExpr)
		case ast.PrimF64:
			g.printf("\t\t%s: C.double(%s),\n", cField, goExpr)
		}
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
			g.printf("\t\t%s: %s(%s),\n", cField, cType, goExpr)
		} else {
			converter := toLowerCamelRaw(t.Name) + "GoToC"
			g.printf("\t\t%s: %s(%s),\n", cField, converter, goExpr)
		}
	}
}

// ─── Dispatch Functions ───

func (g *dispatchCGen) emitDispatchFuncs() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// ─── Dispatch Functions ───\n\n")

	for _, fn := range g.api.Funcs {
		g.emitOneDispatch(fn)
	}
}

func (g *dispatchCGen) emitOneDispatch(fn ast.Func) {
	apiName := g.api.Name
	fnSnake := toSnakeCase(fn.Name)
	dispatchName := apiName + "Dispatch" + toPascalCase(fn.Name)
	wrapperName := fmt.Sprintf("C.call_%s_%s", apiName, fnSnake)
	cbsType := fmt.Sprintf("C.%s_callbacks_t", apiName)

	g.printf("func %s(callbacks unsafe.Pointer, req []byte) ([]byte, error) {\n", dispatchName)
	g.printf("\tcb := (*%s)(callbacks)\n", cbsType)

	// Unmarshal JSON params
	if len(fn.Params) > 0 {
		g.printf("\tvar params struct {\n")
		for _, p := range fn.Params {
			fieldName := toPascalCase(p.Name)
			fieldType := goTypeForDispatch(p.Type)
			jsonTag := toSnakeCase(p.Name)
			g.printf("\t\t%s %s `json:\"%s\"`\n", fieldName, fieldType, jsonTag)
		}
		g.printf("\t}\n")
		g.printf("\tif len(req) > 0 {\n")
		g.printf("\t\tif err := json.Unmarshal(req, &params); err != nil {\n")
		g.printf("\t\t\treturn nil, syscall.EINVAL\n")
		g.printf("\t\t}\n")
		g.printf("\t}\n")
	}

	// Convert Go params → C and build call args
	var callArgs []string
	callArgs = append(callArgs, "cb."+cgoFieldAccess(fnSnake))

	for _, p := range fn.Params {
		cVar := "c" + toPascalCase(p.Name)
		goVar := "params." + toPascalCase(p.Name)
		g.emitParamGoToC(cVar, goVar, p)
		callArgs = append(callArgs, g.paramCallArg(cVar, p)...)
	}

	// Add out params for return type
	if fn.Return != nil {
		g.emitReturnSetup(fn)
		if fn.Return.Kind == ast.TypeSlice {
			callArgs = append(callArgs, "&outPtr", "&outLen")
		} else {
			callArgs = append(callArgs, "&out")
		}
	}

	// Call C wrapper
	g.printf("\trc := %s(%s)\n", wrapperName, strings.Join(callArgs, ", "))
	g.printf("\tif rc != 0 {\n")
	g.printf("\t\treturn nil, syscall.Errno(-rc)\n")
	g.printf("\t}\n")

	// Convert C result → Go and marshal
	if fn.Return != nil {
		g.emitReturnConvert(fn)
	} else {
		g.printf("\treturn nil, nil\n")
	}

	g.printf("}\n\n")
}

func (g *dispatchCGen) emitParamGoToC(cVar, goVar string, p ast.Param) {
	t := p.Type
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimString:
			g.printf("\t%s := C.CString(%s)\n", cVar, goVar)
			g.printf("\tdefer C.free(unsafe.Pointer(%s))\n", cVar)
		case ast.PrimBool:
			g.printf("\t%s := C.bool(%s)\n", cVar, goVar)
		case ast.PrimI32:
			g.printf("\t%s := C.int32_t(%s)\n", cVar, goVar)
		case ast.PrimU32:
			g.printf("\t%s := C.uint32_t(%s)\n", cVar, goVar)
		case ast.PrimI64:
			g.printf("\t%s := C.int64_t(%s)\n", cVar, goVar)
		case ast.PrimU64:
			g.printf("\t%s := C.uint64_t(%s)\n", cVar, goVar)
		case ast.PrimF64:
			g.printf("\t%s := C.double(%s)\n", cVar, goVar)
		}
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			cType := fmt.Sprintf("C.%s_%s_t", g.api.Name, toSnakeCase(t.Name))
			g.printf("\t%s := %s(%s)\n", cVar, cType, goVar)
		} else {
			converter := toLowerCamelRaw(t.Name) + "GoToC"
			g.printf("\t%s := %s(%s)\n", cVar, converter, goVar)
		}
	case ast.TypeArray:
		// Convert Go [N]T → C [N]T element by element.
		elemCType := cTypeForAPICgo(g.api.Name, *t.Elem)
		g.printf("\tvar %s [%d]%s\n", cVar, t.ArrayLen, elemCType)
		g.printf("\tfor i := 0; i < %d; i++ {\n", t.ArrayLen)
		g.printf("\t\t%s[i] = %s(%s[i])\n", cVar, elemCType, goVar)
		g.printf("\t}\n")
	case ast.TypeSlice:
		if t.Elem != nil && t.Elem.Kind == ast.TypePrimitive && t.Elem.Name == ast.PrimString {
			// []string → char** + count
			g.printf("\t%sLen := C.int(len(%s))\n", cVar, goVar)
			g.printf("\t%s := (**C.char)(C.malloc(C.size_t(len(%s)) * C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n", cVar, goVar)
			g.printf("\tdefer C.free(unsafe.Pointer(%s))\n", cVar)
			g.printf("\t%sSlice := unsafe.Slice(%s, len(%s))\n", cVar, cVar, goVar)
			g.printf("\tfor i, s := range %s {\n", goVar)
			g.printf("\t\t%sSlice[i] = C.CString(s)\n", cVar)
			g.printf("\t}\n")
			g.printf("\tdefer func() {\n")
			g.printf("\t\tfor i := range %s {\n", goVar)
			g.printf("\t\t\tC.free(unsafe.Pointer(%sSlice[i]))\n", cVar)
			g.printf("\t\t}\n")
			g.printf("\t}()\n")
		}
	}
}

// paramCallArg returns the C call arguments for a parameter.
// Handles byref (pass pointer), arrays (pass pointer to first element), etc.
func (g *dispatchCGen) paramCallArg(cVar string, p ast.Param) []string {
	switch p.Type.Kind {
	case ast.TypePrimitive:
		if p.ByRef {
			return []string{"&" + cVar}
		}
		return []string{cVar}
	case ast.TypeNamed:
		// Structs always pass by pointer (const or mutable).
		return []string{"&" + cVar}
	case ast.TypeArray:
		// Arrays pass pointer to first element.
		return []string{"&" + cVar + "[0]"}
	case ast.TypeSlice:
		return []string{cVar, cVar + "Len"}
	}
	return []string{cVar}
}

func (g *dispatchCGen) emitReturnSetup(fn ast.Func) {
	ret := fn.Return
	if ret.Kind == ast.TypeSlice {
		elemCType := cTypeForAPICgo(g.api.Name, *ret.Elem)
		g.printf("\tvar outPtr *%s\n", elemCType)
		g.printf("\tvar outLen C.size_t\n")
	} else {
		cType := cTypeForAPICgo(g.api.Name, *ret)
		g.printf("\tvar out %s\n", cType)
	}
}

func (g *dispatchCGen) emitReturnConvert(fn ast.Func) {
	ret := fn.Return

	switch ret.Kind {
	case ast.TypePrimitive:
		switch ret.Name {
		case ast.PrimString:
			g.printf("\tresult := C.GoString(out)\n")
		case ast.PrimBool:
			g.printf("\tresult := bool(out)\n")
		default:
			goType := primitiveToGoType(ret.Name)
			g.printf("\tresult := %s(out)\n", goType)
		}
		g.printf("\treturn json.Marshal(result)\n")

	case ast.TypeNamed:
		if g.isEnum(ret.Name) {
			goType := toPascalCase(ret.Name)
			g.printf("\tresult := %s(out)\n", goType)
		} else {
			converter := toLowerCamelRaw(ret.Name) + "CToGo"
			g.printf("\tresult := %s(&out)\n", converter)
		}
		g.printf("\treturn json.Marshal(result)\n")

	case ast.TypeSlice:
		g.printf("\tn := int(outLen)\n")
		if ret.Elem.Kind == ast.TypeNamed && !g.isEnum(ret.Elem.Name) {
			goElemType := toPascalCase(ret.Elem.Name)
			converter := toLowerCamelRaw(ret.Elem.Name) + "CToGo"
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(outPtr, n)\n")
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			g.printf("\t\t\tresult[i] = %s(&cSlice[i])\n", converter)
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(outPtr))\n")
			g.printf("\t}\n")
		} else {
			goElemType := goTypeForDispatch(*ret.Elem)
			g.printf("\tresult := make([]%s, n)\n", goElemType)
			g.printf("\tif n > 0 {\n")
			g.printf("\t\tcSlice := unsafe.Slice(outPtr, n)\n")
			g.printf("\t\tfor i := 0; i < n; i++ {\n")
			if ret.Elem.Kind == ast.TypePrimitive && ret.Elem.Name == ast.PrimString {
				g.printf("\t\t\tresult[i] = C.GoString(cSlice[i])\n")
			} else {
				g.printf("\t\t\tresult[i] = %s(cSlice[i])\n", goElemType)
			}
			g.printf("\t\t}\n")
			g.printf("\t\tC.free(unsafe.Pointer(outPtr))\n")
			g.printf("\t}\n")
		}
		g.printf("\treturn json.Marshal(result)\n")
	}
}

// ─── APIMeta ───

func (g *dispatchCGen) emitMeta() {
	metaVar := toPascalCase(g.api.Name) + "Meta"
	g.printf("// ─── API Metadata ───\n\n")
	g.printf("var %s = &apiserver.APIMeta{\n", metaVar)
	g.printf("\tName:       %q,\n", g.api.Name)
	g.printf("\tVersion:    %d,\n", g.api.Version)
	g.printf("\tRESTExport: %t,\n", g.api.RestExport)
	g.printf("\tPrefix:     %q,\n", g.api.Prefix)
	g.printf("\tFuncs: []apiserver.FuncMeta{\n")
	for _, fn := range g.api.Funcs {
		dispatchName := g.api.Name + "Dispatch" + toPascalCase(fn.Name)
		g.printf("\t\t{\n")
		g.printf("\t\t\tName:     %q,\n", fn.Name)
		g.printf("\t\t\tMethod:   %q,\n", fn.Method)
		g.printf("\t\t\tPath:     %q,\n", fn.Path)
		g.printf("\t\t\tRTSafe:   %t,\n", fn.RTSafe)
		g.printf("\t\t\tDispatch: %s,\n", dispatchName)
		g.printf("\t\t},\n")
	}
	g.printf("\t},\n")
	g.printf("}\n\n")
}

// ─── Meta Registration ───

func (g *dispatchCGen) emitRegister() {
	metaVar := toPascalCase(g.api.Name) + "Meta"

	g.printf("// ─── Meta Registration ───\n\n")
	g.printf("func init() {\n")
	g.printf("\tapiserver.RegisterMeta(%s)\n", metaVar)
	g.printf("}\n")
}

// ─── Type Helpers ───

// toCTypeForAPI returns the C type string for use in the cgo preamble.
func toCTypeForAPI(apiName string, t ast.TypeRef) string {
	if t.Nullable && t.Kind == ast.TypePrimitive && t.Name == ast.PrimString {
		return "const char *"
	}
	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		elemType := toCTypeForAPI(apiName, *t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		elemType := toCTypeForAPI(apiName, *t.Elem)
		return fmt.Sprintf("%s[%d]", elemType, t.ArrayLen)
	}
	return "void"
}

// cTypeForAPICgo returns the C type for use in Go code (C. prefix).
func cTypeForAPICgo(apiName string, t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case ast.PrimBool:
			return "C.bool"
		case ast.PrimI32:
			return "C.int32_t"
		case ast.PrimU32:
			return "C.uint32_t"
		case ast.PrimI64:
			return "C.int64_t"
		case ast.PrimU64:
			return "C.uint64_t"
		case ast.PrimF64:
			return "C.double"
		case ast.PrimString:
			return "*C.char"
		}
	case ast.TypeNamed:
		return fmt.Sprintf("C.%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		return cTypeForAPICgo(apiName, *t.Elem)
	}
	return "C.int"
}

// goTypeForDispatch returns Go type string for use in dispatch code.
func goTypeForDispatch(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToGoType(t.Name)
		if t.Nullable && t.Name != ast.PrimString {
			return "*" + base
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return "*" + name
		}
		return name
	case ast.TypeSlice:
		return "[]" + goTypeForDispatch(*t.Elem)
	case ast.TypeArray:
		return fmt.Sprintf("[%d]%s", t.ArrayLen, goTypeForDispatch(*t.Elem))
	}
	return "interface{}"
}

// cgoFieldAccess returns the field name for accessing a C struct field from Go.
// Go keywords get a _ prefix in cgo.
func cgoFieldAccess(cFieldName string) string {
	// C keywords get underscore suffix in struct fields (see cSafeName).
	// cgo accesses those escaped names directly.
	if cKeywords[cFieldName] {
		return cFieldName + "_"
	}
	if goKeywords[cFieldName] {
		return "_" + cFieldName
	}
	return cFieldName
}

// toLowerCamelRaw converts snake_case to lowerCamelCase without keyword escaping.
func toLowerCamelRaw(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if i > 0 && len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	result := strings.Join(parts, "")
	if len(result) > 0 {
		result = strings.ToLower(result[:1]) + result[1:]
	}
	return result
}
