// Package cgen generates C source code from a GMI AST.
package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/launcher/internal/gmicompile/ast"
)

// GenerateServerHeader writes C server header (types, callback typedefs, registration).
func GenerateServerHeader(w io.Writer, api *ast.API) error {
	g := &serverGen{w: w, api: api}
	return g.generate()
}

type serverGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *serverGen) generate() error {
	g.emitHeaderGuard()
	g.emitIncludes()
	g.emitEnums()
	g.emitTypes()
	g.emitCallbackTypedefs()
	g.emitCallbacksStruct()
	g.emitRegistration()
	g.emitHeaderGuardEnd()
	return g.err
}

func (g *serverGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *serverGen) emitHeaderGuard() {
	guard := strings.ToUpper(g.api.Name) + "_API_H"
	g.printf("// Generated by gmicompile - DO NOT EDIT\n")
	g.printf("#ifndef %s\n", guard)
	g.printf("#define %s\n\n", guard)
}

func (g *serverGen) emitHeaderGuardEnd() {
	guard := strings.ToUpper(g.api.Name) + "_API_H"
	g.printf("#endif // %s\n", guard)
}

func (g *serverGen) emitIncludes() {
	g.printf("#include <stdint.h>\n")
	g.printf("#include <stdbool.h>\n")
	g.printf("#include <stddef.h>\n")
	g.printf("\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
}

func (g *serverGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// ─── Enums ───\n\n")
	for _, e := range g.api.Enums {
		g.printf("typedef enum {\n")
		for i, v := range e.Values {
			comma := ","
			if i == len(e.Values)-1 {
				comma = ""
			}
			g.printf("    %s_%s = %d%s\n", strings.ToUpper(g.api.Name), v.Name, v.Value, comma)
		}
		g.printf("} %s_%s_t;\n\n", g.api.Name, toSnakeCase(e.Name))
	}
}

func (g *serverGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// ─── Types ───\n\n")
	for _, t := range g.api.Types {
		g.printf("typedef struct {\n")
		for _, f := range t.Fields {
			g.printf("    %s;\n", g.fieldDecl(f))
		}
		g.printf("} %s_%s_t;\n\n", g.api.Name, toSnakeCase(t.Name))
	}
}

func (g *serverGen) fieldDecl(f ast.Field) string {
	cType := g.toCType(f.Type)
	name := toSnakeCase(f.Name)
	return fmt.Sprintf("%s %s", cType, name)
}

func (g *serverGen) toCType(t ast.TypeRef) string {
	if t.Nullable && t.Kind == ast.TypePrimitive && t.Name == "string" {
		return "const char *" // nullable string is just const char* (can be NULL)
	}

	switch t.Kind {
	case ast.TypePrimitive:
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", g.api.Name, toSnakeCase(t.Name))
	case ast.TypeSlice:
		// Slice becomes pointer + length
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s *", elemType)
	case ast.TypeArray:
		elemType := g.toCType(*t.Elem)
		return fmt.Sprintf("%s[%d]", elemType, t.ArrayLen)
	}
	return "void"
}

func primitiveToCType(name string) string {
	switch name {
	case "bool":
		return "bool"
	case "i32":
		return "int32_t"
	case "u32":
		return "uint32_t"
	case "i64":
		return "int64_t"
	case "u64":
		return "uint64_t"
	case "f64":
		return "double"
	case "string":
		return "const char *"
	case "ptr":
		return "void *"
	}
	return "int"
}

func (g *serverGen) emitCallbackTypedefs() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// ─── Callback Typedefs ───\n\n")
	for _, fn := range g.api.Funcs {
		g.printf("typedef int (*%s_%s_fn)(\n", g.api.Name, toSnakeCase(fn.Name))

		// Parameters
		params := []string{}
		for _, p := range fn.Params {
			cType := g.toCType(p.Type)
			// Pass structs by const pointer
			if p.Type.Kind == ast.TypeNamed {
				params = append(params, fmt.Sprintf("const %s *%s", cType, toSnakeCase(p.Name)))
			} else {
				params = append(params, fmt.Sprintf("%s %s", cType, toSnakeCase(p.Name)))
			}
		}

		// Return value as out parameter
		if fn.Return != nil {
			retType := g.toCType(*fn.Return)
			if fn.Return.Kind == ast.TypeSlice {
				// Slice: pointer + out length
				params = append(params, fmt.Sprintf("%s *out", retType))
				params = append(params, "size_t *out_len")
			} else if fn.Return.Kind == ast.TypeNamed || fn.Return.Kind == ast.TypeArray {
				params = append(params, fmt.Sprintf("%s *out", retType))
			} else {
				params = append(params, fmt.Sprintf("%s *out", retType))
			}
		}

		if len(params) == 0 {
			params = append(params, "void")
		}

		for i, p := range params {
			comma := ","
			if i == len(params)-1 {
				comma = ""
			}
			g.printf("    %s%s\n", p, comma)
		}
		g.printf(");\n\n")
	}
}

func (g *serverGen) emitCallbacksStruct() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("// ─── Callbacks Struct ───\n\n")
	g.printf("typedef struct {\n")
	for _, fn := range g.api.Funcs {
		g.printf("    %s_%s_fn %s;\n", g.api.Name, toSnakeCase(fn.Name), toSnakeCase(fn.Name))
	}
	g.printf("} %s_callbacks_t;\n\n", g.api.Name)
}

func (g *serverGen) emitRegistration() {
	g.printf("// ─── Registration ───\n\n")
	g.printf("// Register API callbacks with the launcher.\n")
	g.printf("// instance_name: unique name for this API instance (prepended to REST paths)\n")
	g.printf("// callbacks: struct with function pointers for all API functions\n")
	g.printf("// Returns 0 on success, negative error code on failure.\n")
	g.printf("int %s_api_register(\n", g.api.Name)
	g.printf("    const char *instance_name,\n")
	g.printf("    const %s_callbacks_t *callbacks\n", g.api.Name)
	g.printf(");\n\n")

	g.printf("#ifdef __cplusplus\n}\n#endif\n\n")
}

// toSnakeCase converts CamelCase to snake_case.
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		result.WriteRune(r)
	}
	return strings.ToLower(result.String())
}
