/* Autogenerated by modcompile — do not edit. */

#include "gomc_env.h"
#include "gomc_user.h"
#include <pthread.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>

#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif
#include <unistd.h>
#include <math.h>

/* ---------------------------------------------------------------------------
 * Instance data
 * ------------------------------------------------------------------------- */

typedef struct {
    gomc_hal_float_t *t0_c;
    gomc_hal_float_t *r0;
    gomc_hal_float_t *beta;
    gomc_hal_float_t *r_other;
    gomc_hal_float_t *v_total;
    gomc_hal_float_t *v_thermistor;
    gomc_hal_float_t *temperature_c;
    gomc_hal_float_t *temperature_k;
    gomc_hal_float_t *temperature_f;
    gomc_hal_float_t *resistance;
} inst_hal_t;

typedef struct {
    cmod_t base;
    const cmod_env_t *env;
    int comp_id;
    char name[GOMC_HAL_NAME_LEN + 1];
    inst_hal_t *hal;  /* HAL shared memory portion */
    int exit_fd;        /* eventfd for exit signalling */
    pthread_t thread;   /* user_mainloop thread */
} inst_t;

static void user_mainloop(inst_t *__comp_inst);

/* ---------------------------------------------------------------------------
 * User includes (emitted before convenience macros)
 * ------------------------------------------------------------------------- */

#include <poll.h>

/* ---------------------------------------------------------------------------
 * Convenience defines — user code accesses pins/params by short names.
 * ------------------------------------------------------------------------- */

/* Rewrite user_mainloop(void) → user_mainloop(inst_t *__comp_inst) */
#define user_mainloop(...) user_mainloop(inst_t *__comp_inst)

/* eventfd file descriptor — add to select/poll for clean shutdown. */
#define GOMC_EXIT_FD()      (__comp_inst->exit_fd)
#define GOMC_SHOULD_EXIT()  gomc_should_exit(__comp_inst->exit_fd)

#define FOR_ALL_INSTS() /* userspace — single instance per thread */

#define t0_c (*(__comp_inst->hal->t0_c))
#define r0 (*(__comp_inst->hal->r0))
#define beta (*(__comp_inst->hal->beta))
#define r_other (*(__comp_inst->hal->r_other))
#define v_total (*(__comp_inst->hal->v_total))
#define v_thermistor (*(__comp_inst->hal->v_thermistor))
#define temperature_c (*(__comp_inst->hal->temperature_c))
#define temperature_k (*(__comp_inst->hal->temperature_k))
#define temperature_f (*(__comp_inst->hal->temperature_f))
#define resistance (*(__comp_inst->hal->resistance))

/* RT-safe logging macros */
#define GOMC_LOG_ERR(fmt, ...) gomc_log_errorf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_WARN(fmt, ...) gomc_log_warnf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_INFO(fmt, ...) gomc_log_infof(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_DBG(fmt, ...) gomc_log_debugf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)

/* RTAPI compatibility macros */
#define rtapi_get_time() (__comp_inst->env->rtapi->get_time(__comp_inst->env->rtapi->ctx))

/* ---------------------------------------------------------------------------
 * User code
 * ------------------------------------------------------------------------- */



void user_mainloop(void) {
    int efd = GOMC_EXIT_FD();
    while (!GOMC_SHOULD_EXIT()) {
        FOR_ALL_INSTS() {
            double t0_k = t0_c + 273.15;
            double r_inf;
            double current;

            if (t0_k <= 0.0) {
                goto problem;
            }

            if (r_other <= 0.0) {
                goto problem;
            }

            r_inf = r0 * exp(-beta/t0_k);
            if (r_inf <= 0.0) {
                goto problem;
            }

            current = (v_total - v_thermistor) / r_other;
            if (current <= 0.0) {
                goto problem;
            }

            resistance = v_thermistor / current;
            if (isnan(resistance) || isinf(resistance) || (resistance <= 0.0)) {
                goto problem;
            }

            temperature_k = beta / log(resistance/r_inf);
            if (isnan(temperature_k) || isinf(temperature_k) || (temperature_k < 0.0)) {
                goto problem;
            }

            // no problems found
            goto ok;

problem:
            // override problematic output pins with bogus but not invalid values
            resistance = 0;
            temperature_k = 9999;

ok:
            temperature_c = temperature_k - 273.15;
            temperature_f = (temperature_c * 9.0 / 5.0) + 32.0;
        }
        struct pollfd pfd = { .fd = efd, .events = POLLIN };
        poll(&pfd, 1, 100);
    }
}


/* ---------------------------------------------------------------------------
 * Undefine convenience macros — clean namespace for generated code below.
 * ------------------------------------------------------------------------- */

#undef user_mainloop
#undef GOMC_EXIT_FD
#undef GOMC_SHOULD_EXIT
#undef FOR_ALL_INSTS
#undef t0_c
#undef r0
#undef beta
#undef r_other
#undef v_total
#undef v_thermistor
#undef temperature_c
#undef temperature_k
#undef temperature_f
#undef resistance

/* ---------------------------------------------------------------------------
 * Lifecycle: Init / Start / Stop / Destroy
 * ------------------------------------------------------------------------- */

static void *userspace_thread(void *arg) {
    user_mainloop((inst_t *)arg);
    return NULL;
}

static int inst_start(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    return pthread_create(&inst->thread, NULL, userspace_thread, inst);
}

static void inst_stop(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    gomc_signal_exit(inst->exit_fd);
    pthread_join(inst->thread, NULL);
}

static void inst_destroy(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    if (inst->exit_fd >= 0)
        close(inst->exit_fd);
    if (inst->comp_id > 0)
        inst->env->hal->exit(inst->env->hal->ctx, inst->comp_id);
    inst->env->rtapi->free(inst->env->rtapi->ctx, inst);
}

/* ---------------------------------------------------------------------------
 * Constructor: New()
 * ------------------------------------------------------------------------- */

int New(const cmod_env_t *env, const char *name,
        int argc, const char **argv, cmod_t **out) {
    int r;

    inst_t *inst = (inst_t *)env->rtapi->calloc(env->rtapi->ctx,
                        sizeof(inst_t));
    if (!inst) return -1;

    inst->base.Start   = inst_start;
    inst->base.Stop    = inst_stop;
    inst->base.Destroy = inst_destroy;
    inst->env = env;
    snprintf(inst->name, sizeof(inst->name), "%s", name);

    inst->comp_id = env->hal->init(env->hal->ctx, name,
                                   env->dl_handle, GOMC_HAL_COMP_USER);
    if (inst->comp_id < 0) { env->rtapi->free(env->rtapi->ctx, inst); return -1; }

    inst->exit_fd = eventfd(0, EFD_NONBLOCK | EFD_CLOEXEC);
    if (inst->exit_fd < 0) goto err;

    inst->hal = (inst_hal_t *)env->hal->malloc(env->hal->ctx,
                    sizeof(inst_hal_t));
    if (!inst->hal) goto err;
    memset(inst->hal, 0, sizeof(inst_hal_t));

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->t0_c, inst->comp_id,
            "%s.t0-c", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->r0, inst->comp_id,
            "%s.r0", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->beta, inst->comp_id,
            "%s.beta", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->r_other, inst->comp_id,
            "%s.r-other", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->v_total, inst->comp_id,
            "%s.v-total", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->v_thermistor, inst->comp_id,
            "%s.v-thermistor", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->temperature_c, inst->comp_id,
            "%s.temperature-c", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->temperature_k, inst->comp_id,
            "%s.temperature-k", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->temperature_f, inst->comp_id,
            "%s.temperature-f", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->resistance, inst->comp_id,
            "%s.resistance", name);
    if (r != 0) goto err;

    r = env->hal->ready(env->hal->ctx, inst->comp_id);
    if (r != 0) goto err;

    *out = &inst->base;
    return 0;

err:
    if (inst->exit_fd >= 0) close(inst->exit_fd);
    env->hal->exit(env->hal->ctx, inst->comp_id);
    env->rtapi->free(env->rtapi->ctx, inst);
    return -1;
}
