/* Autogenerated by modcompile — do not edit. */

#include "gomc_env.h"
#include "gomc_user.h"
#include <pthread.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>

#ifndef TRUE
#define TRUE 1
#endif
#ifndef FALSE
#define FALSE 0
#endif

/* ---------------------------------------------------------------------------
 * Instance data
 * ------------------------------------------------------------------------- */

typedef struct {
    gomc_hal_float_t *commanded_frequency;
    gomc_hal_bit_t *reverse;
    gomc_hal_bit_t *run;
    gomc_hal_bit_t *enable;
    gomc_hal_bit_t *is_running;
    gomc_hal_bit_t *is_at_speed;
    gomc_hal_bit_t *is_ready;
    gomc_hal_bit_t *is_alarm;
    gomc_hal_float_t *motor_current;
    gomc_hal_float_t *heatsink_temp;
    gomc_hal_bit_t *watchdog_out;
    gomc_hal_u32_t mbslaveaddr;
} inst_hal_t;

typedef struct {
    cmod_t base;
    const cmod_env_t *env;
    int comp_id;
    char name[GOMC_HAL_NAME_LEN + 1];
    inst_hal_t *hal;  /* HAL shared memory portion */
    int exit_fd;        /* eventfd for exit signalling */
    pthread_t thread;   /* user_mainloop thread */
    const char *_mp_device;
    int _mp_baud;
    int _mp_databits;
    int _mp_stopbits;
    const char *_mp_parity;
    void *_data;
} inst_t;

static void user_mainloop(inst_t *__comp_inst);
static int extra_setup(inst_t *__comp_inst, const char *name, int nparams, const char **params);

/* ---------------------------------------------------------------------------
 * User includes (emitted before convenience macros)
 * ------------------------------------------------------------------------- */

#include<stdio.h>
#include<errno.h>
#include<stdbool.h>
#include<math.h>
#include<modbus.h>
#include<unistd.h>
#include<ctype.h>
#include<poll.h>

/* ---------------------------------------------------------------------------
 * Convenience defines — user code accesses pins/params by short names.
 * ------------------------------------------------------------------------- */

/* Rewrite user_mainloop(void) → user_mainloop(inst_t *__comp_inst) */
#define user_mainloop(...) user_mainloop(inst_t *__comp_inst)

/* eventfd file descriptor — add to select/poll for clean shutdown. */
#define GOMC_EXIT_FD()      (__comp_inst->exit_fd)
#define GOMC_SHOULD_EXIT()  gomc_should_exit(__comp_inst->exit_fd)

#define FOR_ALL_INSTS() /* userspace — single instance per thread */

#define commanded_frequency (*(__comp_inst->hal->commanded_frequency))
#define reverse (*(__comp_inst->hal->reverse))
#define run (*(__comp_inst->hal->run))
#define enable (*(__comp_inst->hal->enable))
#define is_running (*(__comp_inst->hal->is_running))
#define is_at_speed (*(__comp_inst->hal->is_at_speed))
#define is_ready (*(__comp_inst->hal->is_ready))
#define is_alarm (*(__comp_inst->hal->is_alarm))
#define motor_current (*(__comp_inst->hal->motor_current))
#define heatsink_temp (*(__comp_inst->hal->heatsink_temp))
#define watchdog_out (*(__comp_inst->hal->watchdog_out))
#define mbslaveaddr (__comp_inst->hal->mbslaveaddr)
#define data (*(vfd_data*)(__comp_inst->_data))
#define device (__comp_inst->_mp_device)
#define baud (__comp_inst->_mp_baud)
#define databits (__comp_inst->_mp_databits)
#define stopbits (__comp_inst->_mp_stopbits)
#define parity (__comp_inst->_mp_parity)

#undef EXTRA_SETUP
#define EXTRA_SETUP() \
    static int extra_setup(inst_t *__comp_inst, const char *name, int nparams, const char **params)

/* RT-safe logging macros */
#define GOMC_LOG_ERR(fmt, ...) gomc_log_errorf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_WARN(fmt, ...) gomc_log_warnf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_INFO(fmt, ...) gomc_log_infof(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)
#define GOMC_LOG_DBG(fmt, ...) gomc_log_debugf(__comp_inst->env->log, __comp_inst->name, fmt, ##__VA_ARGS__)

/* RTAPI compatibility macros */
#define rtapi_get_time() (__comp_inst->env->rtapi->get_time(__comp_inst->env->rtapi->ctx))

/* ---------------------------------------------------------------------------
 * User code
 * ------------------------------------------------------------------------- */

/*
  Userspace HAL component to control a Hitatchi WJ200 series VFD

  Written by Curtis Dutton, inspired by vfs11_vfd.c in linuxcnc

  Copyright (C) 2012 Curtis Dutton, OK Computers LLC

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation, version 2.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301-1307  USA.

  see 'man wj200_vfd' and the WJ200 section in the Drivers manual.
*/

typedef struct
{
        uint8_t running;
        uint8_t ready;
        uint8_t direction;
        uint8_t at_speed;
        uint8_t alarm;
	float output_current;
	float sink_temp;
        uint16_t frequency;
} wj200_status;

/*sets the operating frequency of the vfd*/
bool wj200_setFrequency(modbus_t* ctx, uint16_t frequency)
{
        return modbus_write_registers(ctx, 0x001, 1, &frequency) > 0;
}

/*resets the trip status of the VFD*/
bool wj200_reset(modbus_t* ctx)
{
        /*after the reset, the wj200 vfd seem to need a second
        before it will reply to more modbus commands*/
        int rc = modbus_write_bit(ctx, 0x003, TRUE);

        sleep(1);

        return rc > 0;
}

bool wj200_setDirection(modbus_t* ctx, bool direction)
{
	return modbus_write_bit(ctx, 0x001, direction) > 0;
}

bool wj200_trip(modbus_t* ctx)
{
        return modbus_write_bit(ctx, 0x002, TRUE) > 0;
}

bool wj200_run(modbus_t* ctx, bool runBit)
{
        return modbus_write_bit(ctx, 0x000, runBit) > 0;
}


bool wj200_getStatus(modbus_t* ctx, wj200_status* status)
{
        int rc;
        uint8_t bits[16];
        uint16_t registers[2];
	uint16_t currentRegister[1];
	uint16_t temperatureRegister[1];

        /*read coils 0x000F thru 0x0019 in one step*/
        rc = modbus_read_bits(ctx, 0x000F-1, 11, bits);

        if(rc < 0)
        {
                return false;
        }

        /*read the first 2 registers*/
        rc = modbus_read_registers(ctx, 0x000, 2, registers);

        if(rc < 0)
        {
                return false;
        }

	// Read 1003h (output current) to 1019h (heatsink temp)
        rc = modbus_read_registers(ctx, 0x1003-1, 1, currentRegister);

        if(rc < 0)
        {
                return false;
        }

	rc = modbus_read_registers(ctx, 0x1019-1, 1, temperatureRegister);

        if(rc < 0)
        {
                return false;
        }


        status->running = bits[0];
        status->direction = bits[1];
        status->ready = bits[2];
        status->alarm = bits[9];
        status->at_speed = bits[5];
        status->frequency = registers[1];
	status->output_current = currentRegister[0];
	status->sink_temp = temperatureRegister[0];

        return true;
}

void print_modbus_error(inst_t *__comp_inst, const char* msg)
{
	GOMC_LOG_ERR(
		"slave(%d): %s - Modbus error (%d) -  %s\n",
		mbslaveaddr,
		msg,
		errno,
		modbus_strerror(errno));
}


/* Per-instance connection state */
typedef struct {
	modbus_t *ctx;
	int init_error;
} vfd_data;

EXTRA_SETUP() {
	(void)nparams; (void)params;  /* unused - using modparams */
	const char *dev = device[0] ? device : "/dev/ttyS0";
	char par = (parity[0] == 'E' || parity[0] == 'e') ? 'E' :
	           (parity[0] == 'O' || parity[0] == 'o') ? 'O' : 'N';

	data.ctx = modbus_new_rtu(dev, baud, par, databits, stopbits);
	if (data.ctx == NULL) {
		GOMC_LOG_ERR("unable to create libmodbus context for %s - %s\n",
			dev, modbus_strerror(errno));
		data.init_error = 1;
		return -1;
	}

	if (modbus_connect(data.ctx)) {
		GOMC_LOG_ERR("unable to connect to %s - %s\n",
			dev, modbus_strerror(errno));
		modbus_free(data.ctx);
		data.ctx = NULL;
		data.init_error = 1;
		return -1;
	}

	data.init_error = 0;
	return 0;
}

void user_mainloop(void) {
	wj200_status status;
	uint16_t calculated_frequency;
    bool last_enable_state = FALSE;
    int efd = GOMC_EXIT_FD();

	if (data.init_error) return;

	while(!GOMC_SHOULD_EXIT()) {
	FOR_ALL_INSTS() {
		/*
                  until the params are set we just wait a bit
		  and then skip to the next instance.

		  if every instance does not get a slave address,
                  this could cause bad behavior
		*/
		if(mbslaveaddr == 0) {
			struct pollfd pfd = { .fd = efd, .events = POLLIN };
			poll(&pfd, 1, 1000);
			continue;
		}

		modbus_set_slave(data.ctx, mbslaveaddr);

		/*
                  for each slave, receive info from the slave,
		  update our output pins based upon vfd status,
		  then set the vfd according to our input pins

		  if we hit an error we just re-loop. The watchdog
		  pin won't change until we make it all the way through
		  the loop.
                */

        if(!wj200_getStatus(data.ctx, &status)) {
            /*
               Only want to list 'failed to get status' once
               any time enable changes - don't spam the output.
               A wink is as good as a nod.
            */
            if (last_enable_state != enable) {
                print_modbus_error(__comp_inst, "failed to get status");
            }
            last_enable_state = enable;
            continue;
        }

		is_running = status.running;
		is_at_speed = status.at_speed;
		is_ready = status.ready;
		is_alarm = status.alarm;

		if(!status.alarm && !enable && !wj200_trip(data.ctx)) {
			print_modbus_error(__comp_inst, "failed to trip");
			continue;
		}
		else if(status.alarm && enable && !wj200_reset(data.ctx)) {
			print_modbus_error(__comp_inst, "failed to reset");
			continue;
		}
		else {
			calculated_frequency = (uint16_t)(fabs(commanded_frequency) * 100);

			if(calculated_frequency != status.frequency
			   && !wj200_setFrequency(data.ctx, calculated_frequency)) {
				print_modbus_error(__comp_inst, "failed to set frequency");
				continue;
			}

			if(reverse != status.direction && !wj200_setDirection(data.ctx, reverse)) {
				print_modbus_error(__comp_inst, "failed to set direction");
				continue;
			}

			if(status.running ^ run && !wj200_run(data.ctx, run)) {
				print_modbus_error(__comp_inst, "failed to run");
				continue;
			}

			watchdog_out = !watchdog_out;
			motor_current = status.output_current / 100;
			heatsink_temp = status.sink_temp / 10;
		}
	}
	}
}


/* ---------------------------------------------------------------------------
 * Undefine convenience macros — clean namespace for generated code below.
 * ------------------------------------------------------------------------- */

#undef user_mainloop
#undef GOMC_EXIT_FD
#undef GOMC_SHOULD_EXIT
#undef FOR_ALL_INSTS
#undef commanded_frequency
#undef reverse
#undef run
#undef enable
#undef is_running
#undef is_at_speed
#undef is_ready
#undef is_alarm
#undef motor_current
#undef heatsink_temp
#undef watchdog_out
#undef mbslaveaddr
#undef data
#undef device
#undef baud
#undef databits
#undef stopbits
#undef parity
#undef EXTRA_SETUP

/* ---------------------------------------------------------------------------
 * Lifecycle: Init / Start / Stop / Destroy
 * ------------------------------------------------------------------------- */

static void *userspace_thread(void *arg) {
    user_mainloop((inst_t *)arg);
    return NULL;
}

static int inst_start(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    return pthread_create(&inst->thread, NULL, userspace_thread, inst);
}

static void inst_stop(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    gomc_signal_exit(inst->exit_fd);
    pthread_join(inst->thread, NULL);
}

static void inst_destroy(cmod_t *self) {
    inst_t *inst = (inst_t *)self;
    if (inst->exit_fd >= 0)
        close(inst->exit_fd);
    if (inst->comp_id > 0)
        inst->env->hal->exit(inst->env->hal->ctx, inst->comp_id);
    if (inst->_data)
        inst->env->rtapi->free(inst->env->rtapi->ctx, inst->_data);
    inst->env->rtapi->free(inst->env->rtapi->ctx, inst);
}

/* ---------------------------------------------------------------------------
 * Constructor: New()
 * ------------------------------------------------------------------------- */

int New(const cmod_env_t *env, const char *name,
        int argc, const char **argv, cmod_t **out) {
    int r;

    inst_t *inst = (inst_t *)env->rtapi->calloc(env->rtapi->ctx,
                        sizeof(inst_t));
    if (!inst) return -1;

    inst->base.Start   = inst_start;
    inst->base.Stop    = inst_stop;
    inst->base.Destroy = inst_destroy;
    inst->env = env;
    snprintf(inst->name, sizeof(inst->name), "%s", name);

    /* modparam: device */
    inst->_mp_device = NULL;
    for (int i = 0; i < argc; i++) {
        if (strncmp(argv[i], "device=", 7) == 0)
            inst->_mp_device = argv[i] + 7;
    }

    /* modparam: baud */
    inst->_mp_baud = 9600;
    for (int i = 0; i < argc; i++) {
        if (strncmp(argv[i], "baud=", 5) == 0)
            inst->_mp_baud = atoi(argv[i] + 5);
    }

    /* modparam: databits */
    inst->_mp_databits = 8;
    for (int i = 0; i < argc; i++) {
        if (strncmp(argv[i], "databits=", 9) == 0)
            inst->_mp_databits = atoi(argv[i] + 9);
    }

    /* modparam: stopbits */
    inst->_mp_stopbits = 1;
    for (int i = 0; i < argc; i++) {
        if (strncmp(argv[i], "stopbits=", 9) == 0)
            inst->_mp_stopbits = atoi(argv[i] + 9);
    }

    /* modparam: parity */
    inst->_mp_parity = NULL;
    for (int i = 0; i < argc; i++) {
        if (strncmp(argv[i], "parity=", 7) == 0)
            inst->_mp_parity = argv[i] + 7;
    }

    inst->comp_id = env->hal->init(env->hal->ctx, name,
                                   env->dl_handle, GOMC_HAL_COMP_USER);
    if (inst->comp_id < 0) { env->rtapi->free(env->rtapi->ctx, inst); return -1; }

    inst->exit_fd = eventfd(0, EFD_NONBLOCK | EFD_CLOEXEC);
    if (inst->exit_fd < 0) goto err;

    inst->hal = (inst_hal_t *)env->hal->malloc(env->hal->ctx,
                    sizeof(inst_hal_t));
    if (!inst->hal) goto err;
    memset(inst->hal, 0, sizeof(inst_hal_t));

    r = extra_setup(inst, name, argc, argv);
    if (r != 0) goto err;

    inst->_data = env->rtapi->calloc(env->rtapi->ctx, sizeof(vfd_data));
    if (!inst->_data) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->commanded_frequency, inst->comp_id,
            "%s.commanded-frequency", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->reverse, inst->comp_id,
            "%s.reverse", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->run, inst->comp_id,
            "%s.run", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_IN,
            &inst->hal->enable, inst->comp_id,
            "%s.enable", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->is_running, inst->comp_id,
            "%s.is-running", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->is_at_speed, inst->comp_id,
            "%s.is-at-speed", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->is_ready, inst->comp_id,
            "%s.is-ready", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->is_alarm, inst->comp_id,
            "%s.is-alarm", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->motor_current, inst->comp_id,
            "%s.motor-current", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_float_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->heatsink_temp, inst->comp_id,
            "%s.heatsink-temp", name);
    if (r != 0) goto err;

    r = gomc_hal_pin_bit_newf(env->hal, GOMC_HAL_OUT,
            &inst->hal->watchdog_out, inst->comp_id,
            "%s.watchdog-out", name);
    if (r != 0) goto err;

    r = gomc_hal_param_u32_newf(env->hal, GOMC_HAL_RW,
            &inst->hal->mbslaveaddr, inst->comp_id,
            "%s.mbslaveaddr", name);
    if (r != 0) goto err;

    r = env->hal->ready(env->hal->ctx, inst->comp_id);
    if (r != 0) goto err;

    *out = &inst->base;
    return 0;

err:
    if (inst->exit_fd >= 0) close(inst->exit_fd);
    env->hal->exit(env->hal->ctx, inst->comp_id);
    env->rtapi->free(env->rtapi->ctx, inst);
    return -1;
}
