// Package pkgreg manages the packages.conf registry and generates
// imports_generated.go for the gomc-server binary.
package pkgreg

import (
"bufio"
"fmt"
"os"
"path/filepath"
"strings"
)

// EntryType identifies the kind of package in the registry.
type EntryType string

const (
TypeGMI   EntryType = "gmi"
TypeGomod EntryType = "gomod"
)

// Entry is one line in packages.conf.
type Entry struct {
Type       EntryType // "gmi" or "gomod"
ImportPath string    // relative import path (e.g. "generated/gmi/kins" or "external/mymodule")
}

// Registry holds the parsed contents of packages.conf.
type Registry struct {
Entries []Entry
}

// GoModule is the Go module path for the gomc-server module.
const GoModule = "github.com/sittner/linuxcnc/src/gomc"

// ReadFile parses a packages.conf file.
func ReadFile(path string) (*Registry, error) {
f, err := os.Open(path)
if err != nil {
return nil, err
}
defer f.Close()

var reg Registry
scanner := bufio.NewScanner(f)
for scanner.Scan() {
line := strings.TrimSpace(scanner.Text())
if line == "" || strings.HasPrefix(line, "#") {
continue
}
fields := strings.Fields(line)
if len(fields) < 2 {
continue
}
reg.Entries = append(reg.Entries, Entry{
Type:       EntryType(fields[0]),
ImportPath: fields[1],
})
}
return &reg, scanner.Err()
}

// WriteFile writes the registry back to packages.conf.
func (r *Registry) WriteFile(path string) error {
var buf strings.Builder
buf.WriteString("# packages.conf — managed by modcompile. DO NOT EDIT MANUALLY.\n")
buf.WriteString("#\n")
buf.WriteString("# Format: TYPE IMPORT_PATH\n")
buf.WriteString("#\n")
buf.WriteString("# TYPE:\n")
buf.WriteString("#   gmi     — generated GMI dispatch package (compiled into gomc-server)\n")
buf.WriteString("#   gomod   — Go module compiled into gomc-server\n")
buf.WriteString("#\n")
buf.WriteString("# IMPORT_PATH — relative path within the gomc module for blank import\n\n")

gmi := r.entriesByType(TypeGMI)
gomod := r.entriesByType(TypeGomod)

if len(gmi) > 0 {
buf.WriteString("# Core GMI dispatch (generated, part of this module)\n")
for _, e := range gmi {
buf.WriteString(fmt.Sprintf("gmi %s\n", e.ImportPath))
}
buf.WriteString("\n")
}

if len(gomod) > 0 {
buf.WriteString("# Go modules (in-tree and installed external)\n")
for _, e := range gomod {
buf.WriteString(fmt.Sprintf("gomod %s\n", e.ImportPath))
}
buf.WriteString("\n")
}

return os.WriteFile(path, []byte(buf.String()), 0644)
}

func (r *Registry) entriesByType(t EntryType) []Entry {
var out []Entry
for _, e := range r.Entries {
if e.Type == t {
out = append(out, e)
}
}
return out
}

// Add adds a new entry to the registry. Returns false if already present.
func (r *Registry) Add(e Entry) bool {
for _, existing := range r.Entries {
if existing.Type == e.Type && existing.ImportPath == e.ImportPath {
return false
}
}
r.Entries = append(r.Entries, e)
return true
}

// Remove removes an entry by import path. Returns false if not found.
func (r *Registry) Remove(importPath string) bool {
for i, e := range r.Entries {
if e.ImportPath == importPath {
r.Entries = append(r.Entries[:i], r.Entries[i+1:]...)
return true
}
}
return false
}

// GenerateImports generates cmd/gomc-server/imports_generated.go from the registry.
func (r *Registry) GenerateImports(serverDir string) error {
path := filepath.Join(serverDir, "cmd", "gomc-server", "imports_generated.go")

var buf strings.Builder
buf.WriteString("// Code generated by modcompile. DO NOT EDIT.\n")
buf.WriteString("package main\n\n")
buf.WriteString("import (\n")

gmi := r.entriesByType(TypeGMI)
gomod := r.entriesByType(TypeGomod)

if len(gmi) > 0 {
buf.WriteString("\t// GMI dispatch packages\n")
for _, e := range gmi {
buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
}
}

if len(gomod) > 0 {
if len(gmi) > 0 {
buf.WriteString("\n")
}
buf.WriteString("\t// Go modules\n")
for _, e := range gomod {
buf.WriteString(fmt.Sprintf("\t_ \"%s/%s\"\n", GoModule, e.ImportPath))
}
}

buf.WriteString(")\n")

if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
return err
}
return os.WriteFile(path, []byte(buf.String()), 0644)
}
