package task

// Code generated by gen_canon_bridge.py - DO NOT EDIT.

/*
#include <stdint.h>
#include <stddef.h>
*/
import "C"
import (
	"runtime/cgo"
	"unsafe"
)

var _ = unsafe.Pointer(nil) // suppress unused import

//export go_canon_init_canon
func go_canon_init_canon(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.InitCanon()
}

//export go_canon_set_g5x_offset
func go_canon_set_g5x_offset(ctx unsafe.Pointer, origin C.int32_t, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetG5xOffset(int32(origin), float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_set_g92_offset
func go_canon_set_g92_offset(ctx unsafe.Pointer, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetG92Offset(float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_set_xy_rotation
func go_canon_set_xy_rotation(ctx unsafe.Pointer, t C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetXYRotation(float64(t))
}

//export go_canon_update_end_point
func go_canon_update_end_point(ctx unsafe.Pointer, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.UpdateEndPoint(float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_use_length_units
func go_canon_use_length_units(ctx unsafe.Pointer, units C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.UseLengthUnits(int32(units))
}

//export go_canon_select_plane
func go_canon_select_plane(ctx unsafe.Pointer, plane C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SelectPlane(int32(plane))
}

//export go_canon_set_traverse_rate
func go_canon_set_traverse_rate(ctx unsafe.Pointer, rate C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetTraverseRate(float64(rate))
}

//export go_canon_straight_traverse
func go_canon_straight_traverse(ctx unsafe.Pointer, lineno C.int32_t, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StraightTraverse(int32(lineno), float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_set_feed_rate
func go_canon_set_feed_rate(ctx unsafe.Pointer, rate C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetFeedRate(float64(rate))
}

//export go_canon_set_feed_reference
func go_canon_set_feed_reference(ctx unsafe.Pointer, reference C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetFeedReference(int32(reference))
}

//export go_canon_set_feed_mode
func go_canon_set_feed_mode(ctx unsafe.Pointer, spindle C.int32_t, mode C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetFeedMode(int32(spindle), int32(mode))
}

//export go_canon_set_motion_control_mode
func go_canon_set_motion_control_mode(ctx unsafe.Pointer, mode C.int32_t, tolerance C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetMotionControlMode(int32(mode), float64(tolerance))
}

//export go_canon_set_naivecam_tolerance
func go_canon_set_naivecam_tolerance(ctx unsafe.Pointer, tolerance C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetNaivecamTolerance(float64(tolerance))
}

//export go_canon_set_cutter_radius_compensation
func go_canon_set_cutter_radius_compensation(ctx unsafe.Pointer, radius C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetCutterRadiusCompensation(float64(radius))
}

//export go_canon_start_cutter_radius_compensation
func go_canon_start_cutter_radius_compensation(ctx unsafe.Pointer, direction C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StartCutterRadiusCompensation(int32(direction))
}

//export go_canon_stop_cutter_radius_compensation
func go_canon_stop_cutter_radius_compensation(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StopCutterRadiusCompensation()
}

//export go_canon_start_speed_feed_synch
func go_canon_start_speed_feed_synch(ctx unsafe.Pointer, spindle C.int32_t, feed_per_revolution C.double, velocity_mode C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StartSpeedFeedSynch(int32(spindle), float64(feed_per_revolution), int32(velocity_mode))
}

//export go_canon_stop_speed_feed_synch
func go_canon_stop_speed_feed_synch(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StopSpeedFeedSynch()
}

//export go_canon_arc_feed
func go_canon_arc_feed(ctx unsafe.Pointer, lineno C.int32_t, first_end C.double, second_end C.double, first_axis C.double, second_axis C.double, rotation C.int32_t, axis_end_point C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ArcFeed(int32(lineno), float64(first_end), float64(second_end), float64(first_axis), float64(second_axis), int32(rotation), float64(axis_end_point), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_straight_feed
func go_canon_straight_feed(ctx unsafe.Pointer, lineno C.int32_t, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StraightFeed(int32(lineno), float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

// go_canon_nurbs_feed is in canon_bridge_manual.go (complex signature)

//export go_canon_rigid_tap
func go_canon_rigid_tap(ctx unsafe.Pointer, lineno C.int32_t, x C.double, y C.double, z C.double, scale C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.RigidTap(int32(lineno), float64(x), float64(y), float64(z), float64(scale))
}

//export go_canon_straight_probe
func go_canon_straight_probe(ctx unsafe.Pointer, lineno C.int32_t, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double, probe_type C.uint8_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StraightProbe(int32(lineno), float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w), uint8(probe_type))
}

//export go_canon_stop
func go_canon_stop(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.Stop()
}

//export go_canon_dwell
func go_canon_dwell(ctx unsafe.Pointer, seconds C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.Dwell(float64(seconds))
}

//export go_canon_finish
func go_canon_finish(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.Finish()
}

//export go_canon_set_spindle_mode
func go_canon_set_spindle_mode(ctx unsafe.Pointer, spindle C.int32_t, mode C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetSpindleMode(int32(spindle), float64(mode))
}

//export go_canon_start_spindle_clockwise
func go_canon_start_spindle_clockwise(ctx unsafe.Pointer, spindle C.int32_t, wait_for_atspeed C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StartSpindleClockwise(int32(spindle), int32(wait_for_atspeed))
}

//export go_canon_start_spindle_counterclockwise
func go_canon_start_spindle_counterclockwise(ctx unsafe.Pointer, spindle C.int32_t, wait_for_atspeed C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StartSpindleCounterclockwise(int32(spindle), int32(wait_for_atspeed))
}

//export go_canon_set_spindle_speed
func go_canon_set_spindle_speed(ctx unsafe.Pointer, spindle C.int32_t, rpm C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetSpindleSpeed(int32(spindle), float64(rpm))
}

//export go_canon_stop_spindle_turning
func go_canon_stop_spindle_turning(ctx unsafe.Pointer, spindle C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StopSpindleTurning(int32(spindle))
}

//export go_canon_orient_spindle
func go_canon_orient_spindle(ctx unsafe.Pointer, spindle C.int32_t, orientation C.double, mode C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.OrientSpindle(int32(spindle), float64(orientation), int32(mode))
}

//export go_canon_wait_spindle_orient_complete
func go_canon_wait_spindle_orient_complete(ctx unsafe.Pointer, spindle C.int32_t, timeout C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.WaitSpindleOrientComplete(int32(spindle), float64(timeout))
}

//export go_canon_select_tool
func go_canon_select_tool(ctx unsafe.Pointer, tool C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SelectTool(int32(tool))
}

//export go_canon_start_change
func go_canon_start_change(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.StartChange()
}

//export go_canon_change_tool
func go_canon_change_tool(ctx unsafe.Pointer, slot C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ChangeTool(int32(slot))
}

//export go_canon_change_tool_number
func go_canon_change_tool_number(ctx unsafe.Pointer, number C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ChangeToolNumber(int32(number))
}

//export go_canon_reload_tooldata
func go_canon_reload_tooldata(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ReloadTooldata()
}

//export go_canon_set_tool_table_entry
func go_canon_set_tool_table_entry(ctx unsafe.Pointer, pocket C.int32_t, toolno C.int32_t, ox C.double, oy C.double, oz C.double, oa C.double, ob C.double, oc C.double, ou C.double, ov C.double, ow C.double, diameter C.double, frontangle C.double, backangle C.double, orientation C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetToolTableEntry(int32(pocket), int32(toolno), float64(ox), float64(oy), float64(oz), float64(oa), float64(ob), float64(oc), float64(ou), float64(ov), float64(ow), float64(diameter), float64(frontangle), float64(backangle), int32(orientation))
}

//export go_canon_use_tool_length_offset
func go_canon_use_tool_length_offset(ctx unsafe.Pointer, x C.double, y C.double, z C.double, a C.double, b C.double, _c C.double, u C.double, v C.double, w C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.UseLengthOffset(float64(x), float64(y), float64(z), float64(a), float64(b), float64(_c), float64(u), float64(v), float64(w))
}

//export go_canon_flood_on
func go_canon_flood_on(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.FloodOn()
}

//export go_canon_flood_off
func go_canon_flood_off(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.FloodOff()
}

//export go_canon_mist_on
func go_canon_mist_on(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.MistOn()
}

//export go_canon_mist_off
func go_canon_mist_off(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.MistOff()
}

//export go_canon_enable_feed_override
func go_canon_enable_feed_override(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.EnableFeedOverride()
}

//export go_canon_disable_feed_override
func go_canon_disable_feed_override(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.DisableFeedOverride()
}

//export go_canon_enable_speed_override
func go_canon_enable_speed_override(ctx unsafe.Pointer, spindle C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.EnableSpeedOverride(int32(spindle))
}

//export go_canon_disable_speed_override
func go_canon_disable_speed_override(ctx unsafe.Pointer, spindle C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.DisableSpeedOverride(int32(spindle))
}

//export go_canon_enable_feed_hold
func go_canon_enable_feed_hold(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.EnableFeedHold()
}

//export go_canon_disable_feed_hold
func go_canon_disable_feed_hold(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.DisableFeedHold()
}

//export go_canon_enable_adaptive_feed
func go_canon_enable_adaptive_feed(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.EnableAdaptiveFeed()
}

//export go_canon_disable_adaptive_feed
func go_canon_disable_adaptive_feed(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.DisableAdaptiveFeed()
}

//export go_canon_set_motion_output_bit
func go_canon_set_motion_output_bit(ctx unsafe.Pointer, index C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetMotionOutputBit(int32(index))
}

//export go_canon_clear_motion_output_bit
func go_canon_clear_motion_output_bit(ctx unsafe.Pointer, index C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ClearMotionOutputBit(int32(index))
}

//export go_canon_set_aux_output_bit
func go_canon_set_aux_output_bit(ctx unsafe.Pointer, index C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetAuxOutputBit(int32(index))
}

//export go_canon_clear_aux_output_bit
func go_canon_clear_aux_output_bit(ctx unsafe.Pointer, index C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ClearAuxOutputBit(int32(index))
}

//export go_canon_set_motion_output_value
func go_canon_set_motion_output_value(ctx unsafe.Pointer, index C.int32_t, value C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetMotionOutputValue(int32(index), float64(value))
}

//export go_canon_set_aux_output_value
func go_canon_set_aux_output_value(ctx unsafe.Pointer, index C.int32_t, value C.double) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetAuxOutputValue(int32(index), float64(value))
}

//export go_canon_wait_input
func go_canon_wait_input(ctx unsafe.Pointer, index C.int32_t, input_type C.int32_t, wait_type C.int32_t, timeout C.double) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.WaitInput(int32(index), int32(input_type), int32(wait_type), float64(timeout)))
}

//export go_canon_clamp_axis
func go_canon_clamp_axis(ctx unsafe.Pointer, axis C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ClampAxis(int32(axis))
}

//export go_canon_unclamp_axis
func go_canon_unclamp_axis(ctx unsafe.Pointer, axis C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.UnclampAxis(int32(axis))
}

//export go_canon_lock_rotary
func go_canon_lock_rotary(ctx unsafe.Pointer, lineno C.int32_t, joint C.int32_t) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.LockRotary(int32(lineno), int32(joint)))
}

//export go_canon_unlock_rotary
func go_canon_unlock_rotary(ctx unsafe.Pointer, lineno C.int32_t, joint C.int32_t) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.UnlockRotary(int32(lineno), int32(joint)))
}

//export go_canon_program_stop
func go_canon_program_stop(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ProgramStop()
}

//export go_canon_optional_program_stop
func go_canon_optional_program_stop(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.OptionalProgramStop()
}

//export go_canon_program_end
func go_canon_program_end(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.ProgramEnd()
}

//export go_canon_pallet_shuttle
func go_canon_pallet_shuttle(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.PalletShuttle()
}

//export go_canon_comment
func go_canon_comment(ctx unsafe.Pointer, s *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.Comment(C.GoString(s))
}

//export go_canon_message
func go_canon_message(ctx unsafe.Pointer, s *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.Message(C.GoString(s))
}

//export go_canon_log_msg
func go_canon_log_msg(ctx unsafe.Pointer, s *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.LogMsg(C.GoString(s))
}

//export go_canon_logopen
func go_canon_logopen(ctx unsafe.Pointer, s *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.LogOpen(C.GoString(s))
}

//export go_canon_logappend
func go_canon_logappend(ctx unsafe.Pointer, s *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.LogAppend(C.GoString(s))
}

//export go_canon_logclose
func go_canon_logclose(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.LogClose()
}

//export go_canon_canon_error
func go_canon_canon_error(ctx unsafe.Pointer, msg *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.CanonError(C.GoString(msg))
}

//export go_canon_turn_probe_on
func go_canon_turn_probe_on(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.TurnProbeOn()
}

//export go_canon_turn_probe_off
func go_canon_turn_probe_off(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.TurnProbeOff()
}

//export go_canon_set_block_delete
func go_canon_set_block_delete(ctx unsafe.Pointer, enabled C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetBlockDelete(int32(enabled))
}

//export go_canon_get_block_delete
func go_canon_get_block_delete(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetBlockDelete())
}

//export go_canon_set_optional_program_stop
func go_canon_set_optional_program_stop(ctx unsafe.Pointer, enabled C.int32_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetOptionalProgramStop(int32(enabled))
}

//export go_canon_get_optional_program_stop
func go_canon_get_optional_program_stop(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetOptionalProgramStop())
}

//export go_canon_update_tag
func go_canon_update_tag(ctx unsafe.Pointer, tag_ptr C.uint64_t) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.UpdateTag(uint64(tag_ptr))
}

//export go_canon_set_parameter_file_name
func go_canon_set_parameter_file_name(ctx unsafe.Pointer, name *C.char) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.SetParameterFileName(C.GoString(name))
}

//export go_canon_on_reset
func go_canon_on_reset(ctx unsafe.Pointer) {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	_canon.OnReset()
}

//export go_canon_get_user_defined_result
func go_canon_get_user_defined_result(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetUserDefinedResult())
}

//export go_canon_get_external_feed_rate
func go_canon_get_external_feed_rate(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalFeedRate())
}

//export go_canon_get_external_traverse_rate
func go_canon_get_external_traverse_rate(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalTraverseRate())
}

//export go_canon_get_external_length_unit_type
func go_canon_get_external_length_unit_type(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalLengthUnitType())
}

//export go_canon_get_external_length_units
func go_canon_get_external_length_units(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalLengthUnits())
}

//export go_canon_get_external_angle_units
func go_canon_get_external_angle_units(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalAngleUnits())
}

//export go_canon_get_external_motion_control_mode
func go_canon_get_external_motion_control_mode(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalMotionControlMode())
}

//export go_canon_get_external_motion_control_tolerance
func go_canon_get_external_motion_control_tolerance(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalMotionControlTolerance())
}

//export go_canon_get_external_motion_control_naivecam_tolerance
func go_canon_get_external_motion_control_naivecam_tolerance(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalMotionControlNaivecamTolerance())
}

//export go_canon_get_external_flood
func go_canon_get_external_flood(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalFlood())
}

//export go_canon_get_external_mist
func go_canon_get_external_mist(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalMist())
}

//export go_canon_get_external_position_x
func go_canon_get_external_position_x(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionX())
}

//export go_canon_get_external_position_y
func go_canon_get_external_position_y(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionY())
}

//export go_canon_get_external_position_z
func go_canon_get_external_position_z(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionZ())
}

//export go_canon_get_external_position_a
func go_canon_get_external_position_a(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionA())
}

//export go_canon_get_external_position_b
func go_canon_get_external_position_b(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionB())
}

//export go_canon_get_external_position_c
func go_canon_get_external_position_c(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionC())
}

//export go_canon_get_external_position_u
func go_canon_get_external_position_u(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionU())
}

//export go_canon_get_external_position_v
func go_canon_get_external_position_v(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionV())
}

//export go_canon_get_external_position_w
func go_canon_get_external_position_w(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalPositionW())
}

//export go_canon_get_external_probe_position_x
func go_canon_get_external_probe_position_x(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionX())
}

//export go_canon_get_external_probe_position_y
func go_canon_get_external_probe_position_y(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionY())
}

//export go_canon_get_external_probe_position_z
func go_canon_get_external_probe_position_z(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionZ())
}

//export go_canon_get_external_probe_position_a
func go_canon_get_external_probe_position_a(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionA())
}

//export go_canon_get_external_probe_position_b
func go_canon_get_external_probe_position_b(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionB())
}

//export go_canon_get_external_probe_position_c
func go_canon_get_external_probe_position_c(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionC())
}

//export go_canon_get_external_probe_position_u
func go_canon_get_external_probe_position_u(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionU())
}

//export go_canon_get_external_probe_position_v
func go_canon_get_external_probe_position_v(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionV())
}

//export go_canon_get_external_probe_position_w
func go_canon_get_external_probe_position_w(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbePositionW())
}

//export go_canon_get_external_probe_value
func go_canon_get_external_probe_value(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalProbeValue())
}

//export go_canon_get_external_probe_tripped_value
func go_canon_get_external_probe_tripped_value(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalProbeTrippedValue())
}

//export go_canon_get_external_speed
func go_canon_get_external_speed(ctx unsafe.Pointer, spindle C.int32_t) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalSpeed(int32(spindle)))
}

//export go_canon_get_external_spindle
func go_canon_get_external_spindle(ctx unsafe.Pointer, spindle C.int32_t) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalSpindle(int32(spindle)))
}

//export go_canon_get_external_tool_length_xoffset
func go_canon_get_external_tool_length_xoffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthXOffset())
}

//export go_canon_get_external_tool_length_yoffset
func go_canon_get_external_tool_length_yoffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthYOffset())
}

//export go_canon_get_external_tool_length_zoffset
func go_canon_get_external_tool_length_zoffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthZOffset())
}

//export go_canon_get_external_tool_length_aoffset
func go_canon_get_external_tool_length_aoffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthAOffset())
}

//export go_canon_get_external_tool_length_boffset
func go_canon_get_external_tool_length_boffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthBOffset())
}

//export go_canon_get_external_tool_length_coffset
func go_canon_get_external_tool_length_coffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthCOffset())
}

//export go_canon_get_external_tool_length_uoffset
func go_canon_get_external_tool_length_uoffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthUOffset())
}

//export go_canon_get_external_tool_length_voffset
func go_canon_get_external_tool_length_voffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthVOffset())
}

//export go_canon_get_external_tool_length_woffset
func go_canon_get_external_tool_length_woffset(ctx unsafe.Pointer) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalToolLengthWOffset())
}

//export go_canon_get_external_tool_slot
func go_canon_get_external_tool_slot(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalToolSlot())
}

//export go_canon_get_external_selected_tool_slot
func go_canon_get_external_selected_tool_slot(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalSelectedToolSlot())
}

// go_canon_get_external_tool_table is in canon_bridge_manual.go (complex signature)

//export go_canon_get_external_tc_fault
func go_canon_get_external_tc_fault(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalTcFault())
}

//export go_canon_get_external_tc_reason
func go_canon_get_external_tc_reason(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalTcReason())
}

//export go_canon_get_external_queue_empty
func go_canon_get_external_queue_empty(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalQueueEmpty())
}

//export go_canon_get_external_axis_mask
func go_canon_get_external_axis_mask(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalAxisMask())
}

//export go_canon_get_external_digital_input
func go_canon_get_external_digital_input(ctx unsafe.Pointer, index C.int32_t, def C.int32_t) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalDigitalInput(int32(index), int32(def)))
}

//export go_canon_get_external_analog_input
func go_canon_get_external_analog_input(ctx unsafe.Pointer, index C.int32_t, def C.double) C.double {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.double(_canon.GetExternalAnalogInput(int32(index), float64(def)))
}

//export go_canon_get_external_feed_override_enable
func go_canon_get_external_feed_override_enable(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalFeedOverrideEnable())
}

//export go_canon_get_external_spindle_override_enable
func go_canon_get_external_spindle_override_enable(ctx unsafe.Pointer, spindle C.int32_t) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalSpindleOverrideEnable(int32(spindle)))
}

//export go_canon_get_external_adaptive_feed_enable
func go_canon_get_external_adaptive_feed_enable(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalAdaptiveFeedEnable())
}

//export go_canon_get_external_feed_hold_enable
func go_canon_get_external_feed_hold_enable(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalFeedHoldEnable())
}

//export go_canon_get_external_plane
func go_canon_get_external_plane(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalPlane())
}

// go_canon_get_external_parameter_file_name is in canon_bridge_manual.go (complex signature)

//export go_canon_get_external_offset_applied
func go_canon_get_external_offset_applied(ctx unsafe.Pointer) C.int32_t {
	_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)
	return C.int32_t(_canon.GetExternalOffsetApplied())
}

// go_canon_get_external_offsets is in canon_bridge_manual.go (complex signature)

