#!/usr/bin/env python3
"""Generate canon_bridge.go and canon_bridge_table.c from canon_api.h.

This reads the generated canon_api.h and produces:
1. canon_bridge.go — //export Go functions that dispatch to Canon methods
2. canon_bridge_table.c — C function that builds the canon_callbacks_t

Usage:
    python3 gen_canon_bridge.py
"""

import re
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(SCRIPT_DIR, "../../generated/gmi/canon/canon_api.h")
OUT_GO = os.path.join(SCRIPT_DIR, "canon_bridge.go")
OUT_C = os.path.join(SCRIPT_DIR, "canon_bridge_table.c")

# Map C types to Go types and cgo types
C_TO_GO = {
    "void": "",
    "int32_t": "C.int32_t",
    "double": "C.double",
    "uint8_t": "C.uint8_t",
    "uint32_t": "C.uint32_t",
    "uint64_t": "C.uint64_t",
    "const char *": "*C.char",
    "const canon_control_point_t *": "unsafe.Pointer",  # handled specially
    "size_t": "C.size_t",
}

# Map C param types to Go Canon method param types
C_TO_GO_CALL = {
    "int32_t": "int32",
    "double": "float64",
    "uint8_t": "uint8",
    "uint32_t": "uint32",
    "uint64_t": "uint64",
}

# Manual overrides for snake_case → Go method name mappings
NAME_OVERRIDES = {
    'set_xy_rotation': 'SetXYRotation',
    'use_tool_length_offset': 'UseLengthOffset',
    'logopen': 'LogOpen',
    'logclose': 'LogClose',
    'logappend': 'LogAppend',
    'logmsg': 'LogMsg',
    'get_external_tool_length_xoffset': 'GetExternalToolLengthXOffset',
    'get_external_tool_length_yoffset': 'GetExternalToolLengthYOffset',
    'get_external_tool_length_zoffset': 'GetExternalToolLengthZOffset',
    'get_external_tool_length_aoffset': 'GetExternalToolLengthAOffset',
    'get_external_tool_length_boffset': 'GetExternalToolLengthBOffset',
    'get_external_tool_length_coffset': 'GetExternalToolLengthCOffset',
    'get_external_tool_length_uoffset': 'GetExternalToolLengthUOffset',
    'get_external_tool_length_voffset': 'GetExternalToolLengthVOffset',
    'get_external_tool_length_woffset': 'GetExternalToolLengthWOffset',
    'get_external_tool_table': 'GetExternalToolTable',
    'canon_error': 'CanonError',
}


# Map from snake_case callback name to Go Canon method name
def snake_to_camel(name):
    """Convert snake_case to CamelCase with overrides."""
    if name in NAME_OVERRIDES:
        return NAME_OVERRIDES[name]
    parts = name.split('_')
    return ''.join(p.capitalize() for p in parts)


def parse_typedefs(header_path):
    """Parse callback typedefs from canon_api.h."""
    with open(header_path) as f:
        content = f.read()

    # Match typedefs like:
    # typedef void (*canon_init_canon_fn)(
    #     void *ctx
    # );
    # or:
    # typedef double (*canon_get_external_position_x_fn)(
    #     void *ctx
    # );
    pattern = re.compile(
        r'typedef\s+(\w+(?:\s*\*)?)\s*\(\*canon_(\w+)_fn\)\(\s*\n(.*?)\);',
        re.DOTALL
    )

    callbacks = []
    for m in pattern.finditer(content):
        ret_type = m.group(1).strip()
        name = m.group(2)
        params_raw = m.group(3)

        # Parse parameters (skip ctx)
        params = []
        for line in params_raw.strip().split('\n'):
            line = line.strip().rstrip(',')
            if not line or line == "void *ctx":
                continue
            # Parse "type name" pairs
            # Handle "const char *msg" or "double x"
            line = line.strip()
            if line.startswith("const canon_control_point_t"):
                # Special: pointer to array + size
                parts = line.split()
                param_name = parts[-1].lstrip('*')
                params.append(("const canon_control_point_t *", param_name))
            elif line.startswith("const char"):
                parts = line.split()
                param_name = parts[-1].lstrip('*')
                params.append(("const char *", param_name))
            else:
                parts = line.rsplit(None, 1)
                if len(parts) == 2:
                    params.append((parts[0], parts[1]))

        callbacks.append({
            'name': name,
            'ret_type': ret_type,
            'params': params,
            'go_method': snake_to_camel(name),
        })

    return callbacks


# Callbacks that need manual implementation due to complex signatures
MANUAL_CALLBACKS = {
    'nurbs_feed',           # control_points array
    'get_external_tool_table',  # out-parameters
    'get_external_offsets',     # out-parameter array
    'get_external_parameter_file_name',  # char** out-param
}


def gen_go_file(callbacks, out_path):
    """Generate canon_bridge.go with //export functions."""
    lines = []
    lines.append('package task')
    lines.append('')
    lines.append('// Code generated by gen_canon_bridge.py - DO NOT EDIT.')
    lines.append('')
    lines.append('/*')
    lines.append('#include <stdint.h>')
    lines.append('#include <stddef.h>')
    lines.append('*/')
    lines.append('import "C"')
    lines.append('import (')
    lines.append('\t"runtime/cgo"')
    lines.append('\t"unsafe"')
    lines.append(')')
    lines.append('')
    lines.append('var _ = unsafe.Pointer(nil) // suppress unused import')
    lines.append('')

    for cb in callbacks:
        name = cb['name']
        ret = cb['ret_type']
        params = cb['params']
        go_method = cb['go_method']

        # Skip manual callbacks — they're in canon_bridge_manual.go
        if name in MANUAL_CALLBACKS:
            lines.append(f'// go_canon_{name} is in canon_bridge_manual.go (complex signature)')
            lines.append('')
            continue

        # Build C parameter list for export function
        c_params = ["ctx unsafe.Pointer"]
        go_args = []

        for p_type, p_name in params:
            # Rename 'c' param to avoid conflict with Go variable names
            safe_name = p_name if p_name != 'c' else '_c'
            if p_type == "const canon_control_point_t *":
                # This is followed by a size param - handle as slice
                c_params.append(f"{safe_name} unsafe.Pointer")
                continue
            elif p_type == "const char *":
                c_params.append(f"{safe_name} *C.char")
                go_args.append(f"C.GoString({safe_name})")
            elif p_type == "size_t":
                c_params.append(f"{safe_name} C.size_t")
                # size param for control_points - skip in Go call
                continue
            elif p_type in C_TO_GO_CALL:
                go_type = C_TO_GO[p_type]
                go_call_type = C_TO_GO_CALL[p_type]
                c_params.append(f"{safe_name} {go_type}")
                go_args.append(f"{go_call_type}({safe_name})")
            else:
                # Unknown type - use as-is
                c_params.append(f"{safe_name} C.int")
                go_args.append(f"int({safe_name})")

        param_str = ", ".join(c_params)
        args_str = ", ".join(go_args)

        # Determine return
        if ret == "void":
            lines.append(f'//export go_canon_{name}')
            lines.append(f'func go_canon_{name}({param_str}) {{')
            lines.append(f'\t_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)')
            lines.append(f'\t_canon.{go_method}({args_str})')
            lines.append('}')
        elif ret == "double":
            lines.append(f'//export go_canon_{name}')
            lines.append(f'func go_canon_{name}({param_str}) C.double {{')
            lines.append(f'\t_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)')
            lines.append(f'\treturn C.double(_canon.{go_method}({args_str}))')
            lines.append('}')
        elif ret in ("int32_t", "int"):
            lines.append(f'//export go_canon_{name}')
            lines.append(f'func go_canon_{name}({param_str}) C.int32_t {{')
            lines.append(f'\t_canon := cgo.Handle(uintptr(ctx)).Value().(*Canon)')
            lines.append(f'\treturn C.int32_t(_canon.{go_method}({args_str}))')
            lines.append('}')
        else:
            lines.append(f'// TODO: unsupported return type {ret} for {name}')

        lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')


def gen_c_file(callbacks, out_path):
    """Generate canon_bridge_table.c with the table builder function."""
    lines = []
    lines.append('// Code generated by gen_canon_bridge.py - DO NOT EDIT.')
    lines.append('')
    lines.append('#define CANON_API_CGO')
    lines.append('#include "../../generated/gmi/canon/canon_api.h"')
    lines.append('#include "_cgo_export.h"')
    lines.append('')
    lines.append('// build_go_canon_callbacks fills a canon_callbacks_t with Go export functions.')
    lines.append('// ctx is a cgo.Handle stored as a uintptr.')
    lines.append('void build_go_canon_callbacks(canon_callbacks_t *cb, void *ctx) {')
    lines.append('    cb->ctx = ctx;')

    for cb in callbacks:
        name = cb['name']
        lines.append(f'    cb->{name} = (canon_{name}_fn)go_canon_{name};')

    lines.append('}')
    lines.append('')

    with open(out_path, 'w') as f:
        f.write('\n'.join(lines))
        f.write('\n')


def main():
    if not os.path.exists(HEADER):
        print(f"Error: {HEADER} not found", file=sys.stderr)
        sys.exit(1)

    callbacks = parse_typedefs(HEADER)
    print(f"Parsed {len(callbacks)} callbacks from canon_api.h")

    gen_go_file(callbacks, OUT_GO)
    print(f"Generated {OUT_GO}")

    gen_c_file(callbacks, OUT_C)
    print(f"Generated {OUT_C}")


if __name__ == '__main__':
    main()
