// Code generated by modcompile. DO NOT EDIT.
package main

import (
	// GMI dispatch packages
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/kins"
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/tp"
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/home"
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/mot"
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/manualtoolchange"
	_ "github.com/sittner/linuxcnc/src/gomc/generated/gmi/halcmd"

	// Go modules
	_ "github.com/sittner/linuxcnc/src/gomc/internal/adsmodule"
)
