// Code generated by modcompile. DO NOT EDIT.
package main

import (
	// GMI dispatch packages
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/halcmd"
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/home"
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/kins"
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/manualtoolchange"
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/mot"
	_ "github.com/sittner/linuxcnc/src/launcher/generated/gmi/tp"

	// Go modules
	_ "github.com/sittner/linuxcnc/src/launcher/internal/adsmodule"
)
