package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateBridgeGo writes a Go file that provides:
//   - A Go interface (<Api>Callbacks) for Go providers to implement
//   - Build<Api>Callbacks(impl) — allocates a C callbacks_t with //export trampolines
//   - //export trampoline functions that dispatch to the Go interface via cgo.Handle
//
// This file goes into the SAME package as the --server-meta output (the cgo dispatch
// package). It uses the same C header and shares types with the _cgo.go file.
func GenerateBridgeGo(w io.Writer, api *ast.API, packageName string) error {
	g := &bridgeGoGen{api: api, w: w, pkg: packageName}
	return g.generate()
}

type bridgeGoGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *bridgeGoGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *bridgeGoGen) generate() error {
	g.emitPreamble()
	g.emitInterface()
	g.emitBuildCallbacks()
	g.emitTrampolines()
	return g.err
}

// --- Preamble ---

func (g *bridgeGoGen) emitPreamble() {
	apiUpper := strings.ToUpper(g.api.Name)
	apiName := g.api.Name

	g.printf("// Code generated by gmicompile --server-go - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)

	// cgo preamble — references same header for callbacks_t type.
	if len(g.api.Imports) > 0 {
		var flags []string
		for _, imp := range g.api.Imports {
			flags = append(flags, fmt.Sprintf("-I../%s", imp.Name))
		}
		g.printf("// #cgo CFLAGS: %s\n", strings.Join(flags, " "))
	}

	g.printf("/*\n")
	g.printf("#define %s_API_CGO\n", apiUpper)
	for _, imp := range g.api.Imports {
		g.printf("#define %s_API_CGO\n", strings.ToUpper(imp.Name))
	}
	g.printf("#include \"%s_api.h\"\n", g.api.Name)
	g.printf("#include <stdlib.h>\n")
	g.printf("#include <string.h>\n")

	// Emit extern declarations for //export trampoline functions.
	// Without these, cgo cannot resolve the function pointer references
	// used in BuildXxxCallbacks.
	g.printf("\n// Forward declarations of //export trampolines\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		g.emitExternDecl(apiName, fn)
	}

	// Emit a static C helper that builds the callbacks struct.
	// This avoids cgo type-system issues with function pointer assignments.
	g.printf("\nstatic %s_callbacks_t *_bridge_build_%s_callbacks(void *ctx) {\n", apiName, apiName)
	g.printf("\t%s_callbacks_t *cbs = calloc(1, sizeof(%s_callbacks_t));\n", apiName, apiName)
	g.printf("\tcbs->ctx = ctx;\n")
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		fnSnake := toSnakeCase(fn.Name)
		// Cast to silence type mismatches between cgo export signatures and typedef fn ptrs
		g.printf("\tcbs->%s = (%s_%s_fn)%s_bridge_%s;\n", fnSnake, apiName, fnSnake, apiName, fnSnake)
	}
	g.printf("\treturn cbs;\n")
	g.printf("}\n")

	g.printf("\n*/\n")
	g.printf("import \"C\"\n\n")

	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"runtime/cgo\"\n")
	if g.hasWatchFuncs() {
		g.printf("\t\"time\"\n")
	}
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	g.printf("var _ = unsafe.Pointer(nil) // suppress unused\n")
	g.printf("var _ = json.Marshal // suppress unused\n")
	if g.hasWatchFuncs() {
		g.printf("var _ time.Duration // suppress unused\n")
	}
	g.printf("\n")
}

// --- Interface ---

func (g *bridgeGoGen) emitInterface() {
	apiPascal := toPascalCase(g.api.Name)
	ifaceName := apiPascal + "Callbacks"

	g.printf("// --- Provider Interface ---\n\n")
	g.printf("// %s defines the API methods that Go providers must implement.\n", ifaceName)
	g.printf("type %s interface {\n", ifaceName)

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue // watch-only, not part of the callback vtable
		}
		methodName := toPascalCase(fn.Name)
		params := g.goMethodParams(fn)
		ret := g.goMethodReturn(fn)
		g.printf("\t%s(%s) %s\n", methodName, params, ret)
	}
	g.printf("}\n\n")
}

// --- BuildCallbacks ---

func (g *bridgeGoGen) emitBuildCallbacks() {
	apiName := g.api.Name
	apiPascal := toPascalCase(apiName)
	cbsType := fmt.Sprintf("C.%s_callbacks_t", apiName)
	ifaceName := apiPascal + "Callbacks"
	funcName := "Build" + apiPascal + "Callbacks"

	g.printf("// --- Callback Builder ---\n\n")
	g.printf("// %s allocates a C %s_callbacks_t struct with function pointers\n", funcName, apiName)
	g.printf("// pointing to //export trampolines that dispatch to the Go interface.\n")
	g.printf("// The returned pointer must be freed with Free%sCallbacks when done.\n", apiPascal)
	g.printf("func %s(impl %s) unsafe.Pointer {\n", funcName, ifaceName)
	g.printf("\th := cgo.NewHandle(impl)\n")
	g.printf("\tcbs := C._bridge_build_%s_callbacks(unsafe.Pointer(h))\n", apiName)
	g.printf("\treturn unsafe.Pointer(cbs)\n")
	g.printf("}\n\n")

	// Free function
	freeName := "Free" + apiPascal + "Callbacks"
	g.printf("// %s releases the cgo.Handle and frees the C struct.\n", freeName)
	g.printf("func %s(ptr unsafe.Pointer) {\n", freeName)
	g.printf("\tcbs := (*%s)(ptr)\n", cbsType)
	g.printf("\tcgo.Handle(cbs.ctx).Delete()\n")
	g.printf("\tC.free(unsafe.Pointer(cbs))\n")
	g.printf("}\n\n")

	// Register function — convenience wrapper that builds callbacks and registers
	regName := "Register" + apiPascal + "API"
	g.printf("// %s registers a Go implementation of the %s API with the apiserver registry.\n", regName, apiName)
	g.printf("func %s(registry *apiserver.Registry, instance string, impl %s) error {\n", regName, ifaceName)
	g.printf("\tptr := %s(impl)\n", funcName)
	g.printf("\treturn registry.Register(%q, %d, instance, ptr)\n", apiName, g.api.Version)
	g.printf("}\n\n")
}

// --- Trampolines ---

func (g *bridgeGoGen) emitTrampolines() {
	apiName := g.api.Name
	apiPascal := toPascalCase(apiName)
	ifaceName := apiPascal + "Callbacks"

	g.printf("// --- //export Trampolines ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Publish {
			continue
		}
		if fn.Watch && fn.Method == "" {
			continue
		}
		g.emitOneTrampoline(apiName, ifaceName, fn)
	}
}

func (g *bridgeGoGen) emitOneTrampoline(apiName, ifaceName string, fn ast.Func) {
	fnSnake := toSnakeCase(fn.Name)
	exportName := fmt.Sprintf("%s_bridge_%s", apiName, fnSnake)
	methodName := toPascalCase(fn.Name)

	// Build C parameter list: void *ctx + C-typed params
	var cParams []string
	cParams = append(cParams, "ctx unsafe.Pointer")

	for _, p := range fn.Params {
		cParams = append(cParams, g.trampolineParam(apiName, p))
		if p.Type.Kind == ast.TypeSlice {
			cParams = append(cParams, fmt.Sprintf("%s_len C.size_t", escapeGoKeyword(p.Name)))
		}
	}

	// Determine C return type
	cRet := ""
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			cRet = fmt.Sprintf(" C.%s_%s_result_t", apiName, fnSnake)
		} else {
			cRet = " " + cTypeForAPICgo(apiName, *fn.Return)
		}
	}

	g.printf("//export %s\n", exportName)
	g.printf("func %s(%s)%s {\n", exportName, strings.Join(cParams, ", "), cRet)

	// Recover the Go impl from cgo.Handle
	g.printf("\timpl := cgo.Handle(ctx).Value().(%s)\n", ifaceName)

	// Convert C params → Go
	var goArgs []string
	for _, p := range fn.Params {
		goArg := g.emitParamCToGo(apiName, p)
		goArgs = append(goArgs, goArg)
	}
	callArgs := strings.Join(goArgs, ", ")

	// Call the Go method
	if fn.Return == nil {
		// Returns error only → map to int32 (0=ok, -1=err) if the C signature expects i32
		g.printf("\terr := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\treturn -1\n")
		g.printf("\t}\n")
		g.printf("\treturn 0\n")
	} else if fn.Return.Kind == ast.TypeSlice {
		// Slice return — allocate C array, convert elements, return _result_t
		fnSnake := toSnakeCase(fn.Name)
		resultType := fmt.Sprintf("C.%s_%s_result_t", apiName, fnSnake)
		elemCType := cTypeForAPICgo(apiName, *fn.Return.Elem)
		isStringSlice := fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == ast.PrimString
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", resultType)
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\tn := len(result)\n")
		g.printf("\tif n == 0 {\n")
		g.printf("\t\treturn %s{}\n", resultType)
		g.printf("\t}\n")
		if isStringSlice {
			// String slices: allocate array of *C.char pointers
			g.printf("\tcArr := (**C.char)(C.calloc(C.size_t(n), C.size_t(unsafe.Sizeof((*C.char)(nil)))))\n")
		} else {
			g.printf("\tcArr := (*%s)(C.calloc(C.size_t(n), C.size_t(unsafe.Sizeof(%s{}))))\n", elemCType, elemCType)
		}
		// NOTE: cArr is NOT added to _freeList — the caller owns and frees the returned slice data.
		g.printf("\tcSlice := unsafe.Slice(cArr, n)\n")
		if fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == ast.PrimString {
			// String slice: each element needs C.CString (caller frees)
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = C.CString(result[i])\n")
			g.printf("\t}\n")
		} else if fn.Return.Elem.Kind == ast.TypeNamed && !g.isEnum(fn.Return.Elem.Name) {
			converter := toLowerCamelRaw(fn.Return.Elem.Name) + "GoToC"
			// Use a no-op freeList — caller owns the returned struct memory including nested strings
			g.printf("\tvar _retFreeList []unsafe.Pointer // not freed: caller owns return data\n")
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = %s(result[i], &_retFreeList)\n", converter)
			g.printf("\t}\n")
		} else {
			g.printf("\tfor i := range result {\n")
			g.printf("\t\tcSlice[i] = %s(result[i])\n", elemCType)
			g.printf("\t}\n")
		}
		g.printf("\tvar out %s\n", resultType)
		g.printf("\tout.data = cArr\n")
		g.printf("\tout.len = C.size_t(n)\n")
		g.printf("\treturn out\n")
	} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimI32 {
		// i32 return — could be error code or value
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\treturn -1\n")
		g.printf("\t}\n")
		g.printf("\treturn C.int32_t(result)\n")
	} else if fn.Return.Kind == ast.TypeNamed {
		// Struct return — convert Go struct to C struct.
		// Caller owns the returned struct and frees its fields.
		converter := toLowerCamelRaw(fn.Return.Name) + "GoToC"
		g.printf("\tvar _retAllocs []unsafe.Pointer // caller owns returned data\n")
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", cTypeForAPICgo(apiName, *fn.Return))
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\treturn %s(*result, &_retAllocs)\n", converter)
	} else if fn.Return.Kind == ast.TypePrimitive && fn.Return.Name == ast.PrimString {
		// String return — use C.CString
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\treturn nil\n")
		g.printf("\t}\n")
		g.printf("\treturn C.CString(result)\n")
	} else {
		// Other primitive returns
		cType := cTypeForAPICgo(apiName, *fn.Return)
		g.printf("\tresult, err := impl.%s(%s)\n", methodName, callArgs)
		g.printf("\tif err != nil {\n")
		g.printf("\t\tvar zero %s\n", cType)
		g.printf("\t\treturn zero\n")
		g.printf("\t}\n")
		g.printf("\treturn %s(result)\n", cType)
	}

	g.printf("}\n\n")
}

// trampolineParam returns the Go parameter declaration for a trampoline (C types).
func (g *bridgeGoGen) trampolineParam(apiName string, p ast.Param) string {
	name := escapeGoKeyword(p.Name)

	if p.IsPtr {
		// opaque pointer — pass through as unsafe.Pointer
		return fmt.Sprintf("%s unsafe.Pointer", name)
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := cTypeForAPICgo(apiName, p.Type)
		if p.ByRef || p.IsOut {
			return fmt.Sprintf("%s *%s", name, cType)
		}
		return fmt.Sprintf("%s %s", name, cType)
	case ast.TypeNamed:
		cType := cTypeForAPICgo(apiName, p.Type)
		if g.isEnum(p.Type.Name) {
			// Enums pass by value
			if p.ByRef || p.IsOut {
				return fmt.Sprintf("%s *%s", name, cType)
			}
			return fmt.Sprintf("%s %s", name, cType)
		}
		// Structs pass by pointer (matches _api.h: const T *param)
		return fmt.Sprintf("%s *%s", name, cType)
	case ast.TypeSlice:
		elemCType := cTypeForAPICgo(apiName, *p.Type.Elem)
		return fmt.Sprintf("%s *%s", name, elemCType)
	}
	return fmt.Sprintf("%s C.int", name)
}

// emitParamCToGo emits conversion code for a single parameter from C to Go
// and returns the Go variable name to pass to the method call.
func (g *bridgeGoGen) emitParamCToGo(apiName string, p ast.Param) string {
	name := escapeGoKeyword(p.Name)
	goVar := "go" + toPascalCase(name)

	if p.IsPtr {
		// opaque ptr: pass as uint64 (same as client_cgo convention)
		g.printf("\t%s := uint64(uintptr(%s))\n", goVar, name)
		return goVar
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		switch p.Type.Name {
		case ast.PrimString:
			g.printf("\t%s := C.GoString(%s)\n", goVar, name)
			return goVar
		case ast.PrimBool:
			g.printf("\t%s := bool(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimI32:
			g.printf("\t%s := int32(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimU32:
			g.printf("\t%s := uint32(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimI64:
			g.printf("\t%s := int64(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimU64:
			g.printf("\t%s := uint64(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimF32:
			g.printf("\t%s := float32(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimF64:
			g.printf("\t%s := float64(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimI8:
			g.printf("\t%s := int8(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		case ast.PrimU8:
			g.printf("\t%s := uint8(%s)\n", goVar, name)
			if p.Type.Nullable {
				return "&" + goVar
			}
			return goVar
		}
	case ast.TypeNamed:
		if g.isEnum(p.Type.Name) {
			goType := toPascalCase(p.Type.Name)
			g.printf("\t%s := %s(%s)\n", goVar, goType, name)
			return goVar
		}
		// Struct: use CToGo converter (defined in _cgo.go)
		// Note: struct params are always pointers in the trampoline signature.
		converter := toLowerCamelRaw(p.Type.Name) + "CToGo"
		if p.ByRef {
			g.printf("\t%s := %s(%s)\n", goVar, converter, name)
			return "&" + goVar
		}
		g.printf("\t%s := %s(%s)\n", goVar, converter, name)
		return goVar
	case ast.TypeSlice:
		// Slice params come with a _len companion
		lenVar := name + "_len"
		if p.Type.Elem.Kind == ast.TypePrimitive && p.Type.Elem.Name == ast.PrimString {
			// String slice: **C.char → []string via C.GoString
			g.printf("\t%sRaw := unsafe.Slice(%s, int(%s))\n", goVar, name, lenVar)
			g.printf("\t%s := make([]string, len(%sRaw))\n", goVar, goVar)
			g.printf("\tfor i := range %sRaw {\n", goVar)
			g.printf("\t\t%s[i] = C.GoString(%sRaw[i])\n", goVar, goVar)
			g.printf("\t}\n")
		} else {
			g.printf("\t%s := unsafe.Slice((*%s)(unsafe.Pointer(%s)), int(%s))\n",
				goVar+"Raw", cTypeForAPICgo(apiName, *p.Type.Elem), name, lenVar)
			// Convert element by element if needed
			if p.Type.Elem.Kind == ast.TypeNamed && !g.isEnum(p.Type.Elem.Name) {
				goElemType := toPascalCase(p.Type.Elem.Name)
				converter := toLowerCamelRaw(p.Type.Elem.Name) + "CToGo"
				g.printf("\t%s := make([]%s, len(%s))\n", goVar, goElemType, goVar+"Raw")
				g.printf("\tfor i := range %s {\n", goVar+"Raw")
				g.printf("\t\t%s[i] = %s(&%s[i])\n", goVar, converter, goVar+"Raw")
				g.printf("\t}\n")
			} else {
				// Primitive slice — direct cast
				goElemType := primitiveToGoType(p.Type.Elem.Name)
				g.printf("\t%s := make([]%s, len(%s))\n", goVar, goElemType, goVar+"Raw")
				g.printf("\tfor i := range %s {\n", goVar+"Raw")
				g.printf("\t\t%s[i] = %s(%s[i])\n", goVar, goElemType, goVar+"Raw")
				g.printf("\t}\n")
			}
		}
		return goVar
	}
	return name
}

// --- Helpers ---

func (g *bridgeGoGen) goMethodParams(fn ast.Func) string {
	parts := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		if p.IsOut {
			continue // out params are returned, not in signature
		}
		paramName := toLowerCamel(p.Name)
		var paramType string
		if p.IsPtr {
			paramType = "uint64"
		} else if p.ByRef && p.Type.Kind == ast.TypeNamed && !g.isEnum(p.Type.Name) {
			paramType = "*" + toPascalCase(p.Type.Name)
		} else {
			paramType = goTypeForDispatch(p.Type)
		}
		parts = append(parts, paramName+" "+paramType)
	}
	return strings.Join(parts, ", ")
}

func (g *bridgeGoGen) goMethodReturn(fn ast.Func) string {
	if fn.Return == nil {
		return "error"
	}
	retType := goTypeForDispatch(*fn.Return)
	if fn.Return.Kind == ast.TypeNamed {
		return fmt.Sprintf("(*%s, error)", retType)
	}
	return fmt.Sprintf("(%s, error)", retType)
}

func (g *bridgeGoGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

func (g *bridgeGoGen) hasWatchFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			return true
		}
	}
	return false
}

// emitExternDecl writes an extern C declaration for a trampoline function.
func (g *bridgeGoGen) emitExternDecl(apiName string, fn ast.Func) {
	fnSnake := toSnakeCase(fn.Name)
	exportName := fmt.Sprintf("%s_bridge_%s", apiName, fnSnake)

	// Return type — slice returns use <api>_<func>_result_t wrapper
	retType := "int32_t" // default for error-only functions
	if fn.Return != nil {
		if fn.Return.Kind == ast.TypeSlice {
			retType = fmt.Sprintf("%s_%s_result_t", apiName, fnSnake)
		} else {
			retType = g.cReturnType(apiName, *fn.Return)
		}
	}

	// Parameters: always starts with void *ctx
	params := []string{"void *ctx"}
	for _, p := range fn.Params {
		params = append(params, g.cParamDecl(apiName, p))
		if p.Type.Kind == ast.TypeSlice {
			params = append(params, "size_t "+p.Name+"_len")
		}
	}

	g.printf("extern %s %s(%s);\n", retType, exportName, strings.Join(params, ", "))
}

// cReturnType returns the C type string for a function return type.
// Uses cgo-compatible types (no const qualifiers) since these are for extern declarations.
func (g *bridgeGoGen) cReturnType(apiName string, t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		if t.Name == ast.PrimString {
			return "char *"
		}
		return primitiveToCType(t.Name)
	case ast.TypeNamed:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Name))
	case ast.TypeSlice:
		return fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(t.Elem.Name))
	}
	return "int32_t"
}

// cParamDecl returns a C parameter declaration string.
func (g *bridgeGoGen) cParamDecl(apiName string, p ast.Param) string {
	name := p.Name
	if p.IsPtr {
		return "void *" + name
	}

	switch p.Type.Kind {
	case ast.TypePrimitive:
		cType := primitiveToCType(p.Type.Name)
		if p.Type.Name == ast.PrimString {
			return "char *" + name
		}
		if p.ByRef || p.IsOut {
			return cType + " *" + name
		}
		return cType + " " + name
	case ast.TypeNamed:
		cType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Name))
		if g.isEnum(p.Type.Name) {
			// Enums pass by value
			if p.ByRef || p.IsOut {
				return cType + " *" + name
			}
			return cType + " " + name
		}
		// Structs always pass by pointer (matches _api.h convention)
		return cType + " *" + name
	case ast.TypeSlice:
		elemCType := fmt.Sprintf("%s_%s_t", apiName, toSnakeCase(p.Type.Elem.Name))
		if p.Type.Elem.Kind == ast.TypePrimitive {
			ct := primitiveToCType(p.Type.Elem.Name)
			if p.Type.Elem.Name == ast.PrimString {
				// cgo exports string slices as char ** (no const)
				return "char **" + name
			}
			elemCType = ct
		}
		return elemCType + " *" + name
	}
	return "int " + name
}
