package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientDartWS writes a Dart WebSocket watch client library.
// Uses the `web_socket_channel` package for the WS connection and supports
// both text (JSON) and binary frames.
func GenerateClientDartWS(w io.Writer, api *ast.API) error {
	g := &clientDartWSGen{w: w, api: api}
	return g.generate()
}

type clientDartWSGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *clientDartWSGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientDartWSGen) generate() error {
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitClient()
	g.emitSubscribeMethods()
	g.emitCommandMethods()
	g.emitClientClose()
	return g.err
}

// --- Header ---

func (g *clientDartWSGen) emitHeader() {
	g.printf("// Code generated by gmicompile --client-dart-ws - DO NOT EDIT.\n")
	g.printf("//\n")
	g.printf("// WebSocket watch client for %s API v%d\n\n", g.api.Name, g.api.Version)
	g.printf("import 'dart:async';\n")
	g.printf("import 'dart:convert';\n")
	g.printf("import 'dart:typed_data';\n")
	g.printf("import 'package:web_socket_channel/web_socket_channel.dart';\n\n")
}

// --- Constants ---

func (g *clientDartWSGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("const int %s = %d;\n", toDartConst(c.Name), c.Value)
	}
	g.printf("\n")
}

// --- Enums ---

func (g *clientDartWSGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		className := toPascalCase(e.Name)
		g.printf("enum %s {\n", className)
		for i, v := range e.Values {
			dartName := toDartEnumValue(v.Name)
			if i < len(e.Values)-1 {
				g.printf("  %s(%d),\n", dartName, v.Value)
			} else {
				g.printf("  %s(%d);\n", dartName, v.Value)
			}
		}
		g.printf("\n")
		g.printf("  final int value;\n")
		g.printf("  const %s(this.value);\n\n", className)
		g.printf("  static %s fromValue(int v) =>\n", className)
		g.printf("      values.firstWhere((e) => e.value == v,\n")
		g.printf("          orElse: () => throw ArgumentError('Unknown %s value: $v'));\n\n", className)
		g.printf("  factory %s.fromJson(dynamic v) => fromValue(v as int);\n", className)
		g.printf("  int toJson() => value;\n")
		g.printf("}\n\n")
	}
}

// --- Types ---

func (g *clientDartWSGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		className := toPascalCase(t.Name)
		g.printf("class %s {\n", className)

		// Fields
		for _, f := range t.Fields {
			dartType := g.toDartType(f.Type)
			fieldName := toDartField(f.Name)
			g.printf("  final %s %s;\n", dartType, fieldName)
		}
		g.printf("\n")

		// Constructor
		g.printf("  const %s({\n", className)
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			if f.Type.Nullable {
				g.printf("    this.%s,\n", fieldName)
			} else {
				g.printf("    required this.%s,\n", fieldName)
			}
		}
		g.printf("  });\n\n")

		// fromJson factory
		g.printf("  factory %s.fromJson(Map<String, dynamic> j) => %s(\n", className, className)
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			jsonKey := toSnakeCase(f.Name)
			g.printf("        %s: %s,\n", fieldName, g.dartFromJson(f.Type, fmt.Sprintf("j['%s']", jsonKey)))
		}
		g.printf("      );\n\n")

		// toJson
		g.printf("  Map<String, dynamic> toJson() => {\n")
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			jsonKey := toSnakeCase(f.Name)
			g.printf("        '%s': %s,\n", jsonKey, g.dartToJson(f.Type, fieldName))
		}
		g.printf("      };\n")

		g.printf("}\n\n")
	}
}

// --- Client ---

func (g *clientDartWSGen) emitClient() {
	className := toPascalCase(g.api.Name) + "WsClient"

	g.printf("// --- WebSocket Client ---\n\n")
	g.printf("class %s {\n", className)
	g.printf("  final String url;\n")
	g.printf("  final String api;\n")
	g.printf("  final String instance;\n\n")

	g.printf("  WebSocketChannel? _channel;\n")
	g.printf("  StreamSubscription? _subscription;\n")
	g.printf("  final _callbacks = <String, void Function(dynamic)>{};\n")
	g.printf("  final _binaryCallbacks = <String, void Function(Uint8List)>{};\n")
	g.printf("  final _pending = <int, Completer<dynamic>>{};\n")
	g.printf("  int _nextId = 1;\n\n")

	// Constructor
	g.printf("  %s({\n", className)
	g.printf("    required this.url,\n")
	g.printf("    this.api = '%s',\n", g.api.Name)
	g.printf("    this.instance = '%s',\n", g.api.Name)
	g.printf("  });\n\n")

	// connect
	g.printf("  void connect() {\n")
	g.printf("    _channel = WebSocketChannel.connect(Uri.parse(url));\n")
	g.printf("    _subscription = _channel!.stream.listen(\n")
	g.printf("      _onMessage,\n")
	g.printf("      onError: (_) {},\n")
	g.printf("      onDone: () {},\n")
	g.printf("    );\n")
	g.printf("  }\n\n")

	// _onMessage
	g.printf("  void _onMessage(dynamic raw) {\n")
	g.printf("    // Binary frame\n")
	g.printf("    if (raw is List<int>) {\n")
	g.printf("      final bytes = raw is Uint8List ? raw : Uint8List.fromList(raw);\n")
	g.printf("      // Binary frames include func name as first null-terminated string\n")
	g.printf("      final nullIdx = bytes.indexOf(0);\n")
	g.printf("      if (nullIdx > 0) {\n")
	g.printf("        final funcName = utf8.decode(bytes.sublist(0, nullIdx));\n")
	g.printf("        final payload = bytes.sublist(nullIdx + 1);\n")
	g.printf("        final cb = _binaryCallbacks[funcName];\n")
	g.printf("        if (cb != null) cb(payload);\n")
	g.printf("      }\n")
	g.printf("      return;\n")
	g.printf("    }\n\n")

	g.printf("    // Text frame (JSON)\n")
	g.printf("    final msg = jsonDecode(raw as String) as Map<String, dynamic>;\n")
	g.printf("    final type = msg['type'] as String?;\n\n")

	g.printf("    if (type == 'update') {\n")
	g.printf("      final funcName = msg['func'] as String?;\n")
	g.printf("      if (funcName != null) {\n")
	g.printf("        final cb = _callbacks[funcName];\n")
	g.printf("        if (cb != null) cb(msg['data']);\n")
	g.printf("      }\n")
	g.printf("    } else if (type == 'result') {\n")
	g.printf("      final id = msg['id'] as int?;\n")
	g.printf("      if (id != null) {\n")
	g.printf("        final completer = _pending.remove(id);\n")
	g.printf("        if (completer != null) {\n")
	g.printf("          final error = msg['error'];\n")
	g.printf("          if (error != null) {\n")
	g.printf("            completer.completeError(Exception(error.toString()));\n")
	g.printf("          } else {\n")
	g.printf("            completer.complete(msg['data']);\n")
	g.printf("          }\n")
	g.printf("        }\n")
	g.printf("      }\n")
	g.printf("    }\n")
	g.printf("  }\n\n")

	// _send
	g.printf("  void _send(Map<String, dynamic> msg) {\n")
	g.printf("    _channel?.sink.add(jsonEncode(msg));\n")
	g.printf("  }\n\n")

	// subscribe (generic)
	g.printf("  void subscribe(String funcName, int rateMs, void Function(dynamic) callback) {\n")
	g.printf("    _callbacks[funcName] = callback;\n")
	g.printf("    _send({\n")
	g.printf("      'action': 'subscribe',\n")
	g.printf("      'api': api,\n")
	g.printf("      'instance': instance,\n")
	g.printf("      'func': funcName,\n")
	g.printf("      'rate_ms': rateMs,\n")
	g.printf("    });\n")
	g.printf("  }\n\n")

	// subscribeBinary (generic)
	g.printf("  void subscribeBinary(String funcName, int rateMs, void Function(Uint8List) callback) {\n")
	g.printf("    _binaryCallbacks[funcName] = callback;\n")
	g.printf("    _send({\n")
	g.printf("      'action': 'subscribe',\n")
	g.printf("      'api': api,\n")
	g.printf("      'instance': instance,\n")
	g.printf("      'func': funcName,\n")
	g.printf("      'rate_ms': rateMs,\n")
	g.printf("    });\n")
	g.printf("  }\n\n")

	// unsubscribe
	g.printf("  void unsubscribe(String funcName) {\n")
	g.printf("    _callbacks.remove(funcName);\n")
	g.printf("    _binaryCallbacks.remove(funcName);\n")
	g.printf("    _send({\n")
	g.printf("      'action': 'unsubscribe',\n")
	g.printf("      'api': api,\n")
	g.printf("      'instance': instance,\n")
	g.printf("      'func': funcName,\n")
	g.printf("    });\n")
	g.printf("  }\n\n")

	// call (generic command)
	g.printf("  Future<dynamic> call(String funcName, [Map<String, dynamic>? args]) async {\n")
	g.printf("    final id = _nextId++;\n")
	g.printf("    final completer = Completer<dynamic>();\n")
	g.printf("    _pending[id] = completer;\n")
	g.printf("    _send({\n")
	g.printf("      'action': 'call',\n")
	g.printf("      'api': api,\n")
	g.printf("      'instance': instance,\n")
	g.printf("      'func': funcName,\n")
	g.printf("      'id': id,\n")
	g.printf("      'args': args ?? {},\n")
	g.printf("    });\n")
	g.printf("    return completer.future;\n")
	g.printf("  }\n\n")
}

// --- Typed Subscribe Methods ---

func (g *clientDartWSGen) emitSubscribeMethods() {
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			continue
		}
		methodName := "watch" + toPascalCase(fn.Name)
		defaultRate := g.defaultRateMS(fn)

		// Check if this is a binary watch function (returns []u8)
		isBinary := g.isBinaryWatch(fn)

		if isBinary {
			g.printf("  /// Subscribe to %s updates (binary frames).\n", fn.Name)
			g.printf("  void %s({int rateMs = %s, required void Function(Uint8List) onData}) {\n",
				methodName, defaultRate)
			g.printf("    subscribeBinary('%s', rateMs, onData);\n", fn.Name)
			g.printf("  }\n\n")
		} else if fn.Return != nil && fn.Return.Kind == ast.TypeNamed {
			typeName := toPascalCase(fn.Return.Name)
			g.printf("  /// Subscribe to %s updates.\n", fn.Name)
			g.printf("  void %s({int rateMs = %s, required void Function(%s) onData}) {\n",
				methodName, defaultRate, typeName)
			g.printf("    subscribe('%s', rateMs, (data) {\n", fn.Name)
			g.printf("      if (data is Map<String, dynamic>) {\n")
			g.printf("        onData(%s.fromJson(data));\n", typeName)
			g.printf("      }\n")
			g.printf("    });\n")
			g.printf("  }\n\n")
		} else {
			g.printf("  /// Subscribe to %s updates.\n", fn.Name)
			g.printf("  void %s({int rateMs = %s, required void Function(dynamic) onData}) {\n",
				methodName, defaultRate)
			g.printf("    subscribe('%s', rateMs, onData);\n", fn.Name)
			g.printf("  }\n\n")
		}
	}
}

// --- Typed Command Methods ---

func (g *clientDartWSGen) emitCommandMethods() {
	hasCommands := false
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			hasCommands = true
			break
		}
	}
	if !hasCommands {
		return
	}

	g.printf("  // --- Command Methods ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue
		}
		methodName := toDartMethod(fn.Name)
		retType := g.methodReturnType(fn)
		params := g.methodParamsWS(fn)

		g.printf("  Future<%s> %s(%s) async {\n", retType, methodName, params)

		if len(fn.Params) > 0 {
			g.printf("    final args = <String, dynamic>{\n")
			for _, p := range fn.Params {
				paramName := toDartField(p.Name)
				g.printf("      '%s': %s,\n", toSnakeCase(p.Name), g.dartToJson(p.Type, paramName))
			}
			g.printf("    };\n")
			if fn.Return == nil {
				g.printf("    await call('%s', args);\n", fn.Name)
			} else {
				g.printf("    final result = await call('%s', args);\n", fn.Name)
				g.emitReturnCast(fn, retType)
			}
		} else {
			if fn.Return == nil {
				g.printf("    await call('%s');\n", fn.Name)
			} else {
				g.printf("    final result = await call('%s');\n", fn.Name)
				g.emitReturnCast(fn, retType)
			}
		}
		g.printf("  }\n\n")
	}
}

// emitReturnCast writes the return statement with proper type casting for WS results.
func (g *clientDartWSGen) emitReturnCast(fn ast.Func, retType string) {
	if fn.Return == nil {
		return
	}
	if fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil && fn.Return.Elem.Kind == ast.TypeNamed {
		elemClass := toPascalCase(fn.Return.Elem.Name)
		g.printf("    return (result as List? ?? []).map((e) => %s.fromJson(e as Map<String, dynamic>)).toList();\n", elemClass)
	} else if fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil && fn.Return.Elem.Kind == ast.TypePrimitive {
		elemType := g.toDartType(*fn.Return.Elem)
		g.printf("    return (result as List).cast<%s>();\n", elemType)
	} else if fn.Return.Kind == ast.TypeNamed {
		retClass := toPascalCase(fn.Return.Name)
		g.printf("    return %s.fromJson(result as Map<String, dynamic>);\n", retClass)
	} else {
		g.printf("    return result as %s;\n", retType)
	}
}

func (g *clientDartWSGen) emitClientClose() {
	g.printf("  /// Close the WebSocket connection.\n")
	g.printf("  Future<void> dispose() async {\n")
	g.printf("    _callbacks.clear();\n")
	g.printf("    _binaryCallbacks.clear();\n")
	g.printf("    await _subscription?.cancel();\n")
	g.printf("    await _channel?.sink.close();\n")
	g.printf("  }\n")
	g.printf("}\n")
}

// --- Helpers ---

func (g *clientDartWSGen) isBinaryWatch(fn ast.Func) bool {
	// A watch function returning []u8 is treated as binary
	if fn.Return != nil && fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil {
		return fn.Return.Elem.Kind == ast.TypePrimitive && fn.Return.Elem.Name == "u8"
	}
	return false
}

func (g *clientDartWSGen) defaultRateMS(fn ast.Func) string {
	if fn.WatchDefaultRate != "" {
		return parseRateToMS(fn.WatchDefaultRate)
	}
	return "100"
}

func (g *clientDartWSGen) methodParamsWS(fn ast.Func) string {
	if len(fn.Params) == 0 {
		return ""
	}
	var required []string
	var optional []string
	for _, p := range fn.Params {
		paramName := toDartField(p.Name)
		if p.Type.Nullable {
			// toDartType already appends ? for nullable types
			dartType := g.toDartType(p.Type)
			optional = append(optional, fmt.Sprintf("%s %s", dartType, paramName))
		} else {
			dartType := g.toDartType(p.Type)
			required = append(required, fmt.Sprintf("required %s %s", dartType, paramName))
		}
	}
	all := append(required, optional...)
	return "{" + strings.Join(all, ", ") + "}"
}

func (g *clientDartWSGen) methodReturnType(fn ast.Func) string {
	if fn.Return == nil {
		return "void"
	}
	return g.toDartType(*fn.Return)
}

func (g *clientDartWSGen) toDartType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToDartType(t.Name)
		if t.Nullable {
			return base + "?"
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return name + "?"
		}
		return name
	case ast.TypeSlice:
		elem := g.toDartType(*t.Elem)
		return "List<" + elem + ">"
	case ast.TypeArray:
		elem := g.toDartType(*t.Elem)
		return "List<" + elem + ">"
	}
	return "dynamic"
}

func (g *clientDartWSGen) dartFromJson(t ast.TypeRef, expr string) string {
	if t.Nullable {
		inner := t
		inner.Nullable = false
		return fmt.Sprintf("%s == null ? null : %s", expr, g.dartFromJson(inner, expr))
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("(%s as bool?) ?? false", expr)
		case "string":
			return fmt.Sprintf("(%s as String?) ?? ''", expr)
		case "f32", "f64":
			return fmt.Sprintf("(%s as num?)?.toDouble() ?? 0.0", expr)
		default:
			return fmt.Sprintf("(%s as num?)?.toInt() ?? 0", expr)
		}
	case ast.TypeNamed:
		className := toPascalCase(t.Name)
		if g.isEnum(t.Name) {
			return fmt.Sprintf("%s.fromValue((%s as num?)?.toInt() ?? 0)", className, expr)
		}
		return fmt.Sprintf("%s.fromJson(%s as Map<String, dynamic>)", className, expr)
	case ast.TypeSlice, ast.TypeArray:
		elemExpr := g.dartFromJson(*t.Elem, "e")
		return fmt.Sprintf("(%s as List? ?? []).map((e) => %s).toList()", expr, elemExpr)
	}
	return expr
}

func (g *clientDartWSGen) dartToJson(t ast.TypeRef, expr string) string {
	if t.Nullable {
		inner := t
		inner.Nullable = false
		return fmt.Sprintf("%s == null ? null : %s", expr, g.dartToJson(inner, expr+"!"))
	}
	switch t.Kind {
	case ast.TypePrimitive:
		return expr
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			return expr + ".value"
		}
		return expr + ".toJson()"
	case ast.TypeSlice, ast.TypeArray:
		elemExpr := g.dartToJson(*t.Elem, "e")
		if elemExpr == "e" {
			return expr
		}
		return fmt.Sprintf("%s.map((e) => %s).toList()", expr, elemExpr)
	}
	return expr
}

func (g *clientDartWSGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}
