package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateClientDart writes a Dart REST client library for calling the API
// over HTTP/JSON. Uses the `http` package for HTTP requests.
func GenerateClientDart(w io.Writer, api *ast.API) error {
	g := &clientDartGen{w: w, api: api}
	return g.generate()
}

type clientDartGen struct {
	w   io.Writer
	api *ast.API
	err error
}

func (g *clientDartGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *clientDartGen) generate() error {
	g.emitHeader()
	g.emitConstants()
	g.emitEnums()
	g.emitTypes()
	g.emitClient()
	g.emitClientMethods()
	return g.err
}

// --- Header ---

func (g *clientDartGen) emitHeader() {
	g.printf("// Code generated by gmicompile --client-dart - DO NOT EDIT.\n")
	g.printf("//\n")
	g.printf("// REST client for %s API v%d\n\n", g.api.Name, g.api.Version)
	g.printf("import 'dart:convert';\n")
	g.printf("import 'package:http/http.dart' as http;\n\n")
}

// --- Constants ---

func (g *clientDartGen) emitConstants() {
	if len(g.api.Consts) == 0 {
		return
	}
	g.printf("// --- Constants ---\n\n")
	for _, c := range g.api.Consts {
		g.printf("const int %s = %d;\n", toDartConst(c.Name), c.Value)
	}
	g.printf("\n")
}

// --- Enums ---

func (g *clientDartGen) emitEnums() {
	if len(g.api.Enums) == 0 {
		return
	}
	g.printf("// --- Enums ---\n\n")
	for _, e := range g.api.Enums {
		className := toPascalCase(e.Name)
		g.printf("enum %s {\n", className)
		for i, v := range e.Values {
			dartName := toDartEnumValue(v.Name)
			if i < len(e.Values)-1 {
				g.printf("  %s(%d),\n", dartName, v.Value)
			} else {
				g.printf("  %s(%d);\n", dartName, v.Value)
			}
		}
		g.printf("\n")
		g.printf("  final int value;\n")
		g.printf("  const %s(this.value);\n\n", className)
		g.printf("  static %s fromValue(int v) =>\n", className)
		g.printf("      values.firstWhere((e) => e.value == v,\n")
		g.printf("          orElse: () => throw ArgumentError('Unknown %s value: $v'));\n\n", className)
		g.printf("  factory %s.fromJson(dynamic v) => fromValue(v as int);\n", className)
		g.printf("  int toJson() => value;\n")
		g.printf("}\n\n")
	}
}

// --- Types ---

func (g *clientDartGen) emitTypes() {
	if len(g.api.Types) == 0 {
		return
	}
	g.printf("// --- Types ---\n\n")
	for _, t := range g.api.Types {
		className := toPascalCase(t.Name)
		g.printf("class %s {\n", className)

		// Fields
		for _, f := range t.Fields {
			dartType := g.toDartType(f.Type)
			fieldName := toDartField(f.Name)
			g.printf("  final %s %s;\n", dartType, fieldName)
		}
		g.printf("\n")

		// Constructor
		g.printf("  const %s({\n", className)
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			if f.Type.Nullable {
				g.printf("    this.%s,\n", fieldName)
			} else {
				g.printf("    required this.%s,\n", fieldName)
			}
		}
		g.printf("  });\n\n")

		// fromJson factory
		g.printf("  factory %s.fromJson(Map<String, dynamic> j) => %s(\n", className, className)
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			jsonKey := toSnakeCase(f.Name)
			g.printf("        %s: %s,\n", fieldName, g.dartFromJson(f.Type, fmt.Sprintf("j['%s']", jsonKey)))
		}
		g.printf("      );\n\n")

		// toJson method
		g.printf("  Map<String, dynamic> toJson() => {\n")
		for _, f := range t.Fields {
			fieldName := toDartField(f.Name)
			jsonKey := toSnakeCase(f.Name)
			g.printf("        '%s': %s,\n", jsonKey, g.dartToJson(f.Type, fieldName))
		}
		g.printf("      };\n")

		g.printf("}\n\n")
	}
}

// --- Client ---

func (g *clientDartGen) emitClient() {
	className := toPascalCase(g.api.Name) + "Client"

	g.printf("// --- Client ---\n\n")

	// APIError
	g.printf("class ApiError implements Exception {\n")
	g.printf("  final int statusCode;\n")
	g.printf("  final String message;\n\n")
	g.printf("  ApiError(this.statusCode, this.message);\n\n")
	g.printf("  @override\n")
	g.printf("  String toString() => '$message (HTTP $statusCode)';\n")
	g.printf("}\n\n")

	// Client class
	g.printf("class %s {\n", className)
	g.printf("  final String baseUrl;\n")
	g.printf("  final http.Client _http;\n\n")

	// Constructor
	g.printf("  %s({required this.baseUrl, http.Client? client})\n", className)
	g.printf("      : _http = client ?? http.Client();\n\n")

	// _doRequest helper
	g.printf("  Future<dynamic> _doRequest(\n")
	g.printf("    String method,\n")
	g.printf("    String path, {\n")
	g.printf("    Object? body,\n")
	g.printf("    bool hasResult = false,\n")
	g.printf("  }) async {\n")
	g.printf("    final url = Uri.parse('$baseUrl/api/v1/%s$path');\n", g.api.Prefix)
	g.printf("    final headers = <String, String>{'Accept': 'application/json'};\n")
	g.printf("    String? encodedBody;\n")
	g.printf("    if (body != null) {\n")
	g.printf("      headers['Content-Type'] = 'application/json';\n")
	g.printf("      encodedBody = jsonEncode(body);\n")
	g.printf("    }\n\n")

	g.printf("    final http.Response resp;\n")
	g.printf("    switch (method) {\n")
	g.printf("      case 'GET':\n")
	g.printf("        resp = await _http.get(url, headers: headers);\n")
	g.printf("      case 'POST':\n")
	g.printf("        resp = await _http.post(url, headers: headers, body: encodedBody);\n")
	g.printf("      case 'PUT':\n")
	g.printf("        resp = await _http.put(url, headers: headers, body: encodedBody);\n")
	g.printf("      case 'DELETE':\n")
	g.printf("        resp = await _http.delete(url, headers: headers);\n")
	g.printf("      default:\n")
	g.printf("        throw ArgumentError('Unsupported HTTP method: $method');\n")
	g.printf("    }\n\n")

	g.printf("    if (resp.statusCode >= 400) {\n")
	g.printf("      String msg;\n")
	g.printf("      try {\n")
	g.printf("        final err = jsonDecode(resp.body) as Map<String, dynamic>;\n")
	g.printf("        msg = (err['error'] as String?) ?? resp.body;\n")
	g.printf("      } catch (_) {\n")
	g.printf("        msg = resp.body;\n")
	g.printf("      }\n")
	g.printf("      throw ApiError(resp.statusCode, msg);\n")
	g.printf("    }\n\n")

	g.printf("    if (hasResult && resp.body.isNotEmpty) {\n")
	g.printf("      return jsonDecode(resp.body);\n")
	g.printf("    }\n")
	g.printf("    return null;\n")
	g.printf("  }\n\n")
}

// --- Client Methods ---

func (g *clientDartGen) emitClientMethods() {
	if len(g.api.Funcs) == 0 {
		return
	}
	g.printf("  // --- API Methods ---\n\n")

	for _, fn := range g.api.Funcs {
		if fn.Watch {
			continue // watch functions are in the WS client
		}
		g.emitClientMethod(fn)
	}

	g.printf("}\n")
}

func (g *clientDartGen) emitClientMethod(fn ast.Func) {
	methodName := toDartMethod(fn.Name)

	// Return type
	retType := g.methodReturnType(fn)

	// Params
	params := g.methodParams(fn)

	g.printf("  Future<%s> %s(%s) async {\n", retType, methodName, params)

	// Build path
	path := fn.Path
	pathParams := extractPathParams(path)

	if len(pathParams) > 0 {
		g.printf("    var path = '%s';\n", path)
		for _, pp := range pathParams {
			paramName := toDartField(pp)
			g.printf("    path = path.replaceFirst('{%s}', Uri.encodeComponent(%s.toString()));\n", pp, paramName)
		}
	} else {
		g.printf("    const path = '%s';\n", path)
	}

	// Query parameters (GET/DELETE)
	queryParams := g.nonPathParams(fn, pathParams)
	if len(queryParams) > 0 && (fn.Method == "GET" || fn.Method == "DELETE" || fn.Method == "") {
		g.printf("    final query = <String, String>{\n")
		for _, qp := range queryParams {
			paramName := toDartField(qp.Name)
			if qp.Type.Nullable {
				g.printf("      if (%s != null) '%s': %s.toString(),\n", paramName, toSnakeCase(qp.Name), paramName)
			} else {
				g.printf("      '%s': %s.toString(),\n", toSnakeCase(qp.Name), paramName)
			}
		}
		g.printf("    };\n")
		g.printf("    final queryPath = query.isNotEmpty\n")
		g.printf("        ? '$path?${query.entries.map((e) => '${e.key}=${Uri.encodeComponent(e.value)}').join('&')}'\n")
		g.printf("        : path;\n")
	}

	// Body (POST/PUT/PATCH)
	var bodyExpr string
	method := fn.Method
	if method == "" {
		method = "GET"
	}

	if len(queryParams) > 0 && (fn.Method == "POST" || fn.Method == "PUT" || fn.Method == "PATCH") {
		// Check if there's a single struct param — pass its toJson() directly
		if len(queryParams) == 1 && queryParams[0].Type.Kind == ast.TypeNamed {
			bodyExpr = toDartField(queryParams[0].Name) + ".toJson()"
		} else {
			g.printf("    final body = {\n")
			for _, bp := range queryParams {
				paramName := toDartField(bp.Name)
				g.printf("      '%s': %s,\n", toSnakeCase(bp.Name), g.dartToJson(bp.Type, paramName))
			}
			g.printf("    };\n")
			bodyExpr = "body"
		}
	} else {
		bodyExpr = "null"
	}

	// Determine path variable name
	pathVar := "path"
	if len(queryParams) > 0 && (fn.Method == "GET" || fn.Method == "DELETE" || fn.Method == "") {
		pathVar = "queryPath"
	}

	// Make request
	hasResult := fn.Return != nil
	if !hasResult {
		g.printf("    await _doRequest('%s', %s, body: %s);\n", method, pathVar, bodyExpr)
	} else {
		g.printf("    final result = await _doRequest('%s', %s, body: %s, hasResult: true);\n", method, pathVar, bodyExpr)
		// Convert result
		if fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil && fn.Return.Elem.Kind == ast.TypeNamed {
			elemClass := toPascalCase(fn.Return.Elem.Name)
			g.printf("    return (result as List? ?? []).map((e) => %s.fromJson(e as Map<String, dynamic>)).toList();\n", elemClass)
		} else if fn.Return.Kind == ast.TypeSlice && fn.Return.Elem != nil && fn.Return.Elem.Kind == ast.TypePrimitive {
			elemType := g.toDartType(*fn.Return.Elem)
			g.printf("    return (result as List).cast<%s>();\n", elemType)
		} else if fn.Return.Kind == ast.TypeNamed {
			retClass := toPascalCase(fn.Return.Name)
			g.printf("    return %s.fromJson(result as Map<String, dynamic>);\n", retClass)
		} else {
			g.printf("    return result as %s;\n", retType)
		}
	}
	g.printf("  }\n\n")
}

// --- Helpers ---

func (g *clientDartGen) methodParams(fn ast.Func) string {
	if len(fn.Params) == 0 {
		return ""
	}
	var required []string
	var optional []string
	for _, p := range fn.Params {
		paramName := toDartField(p.Name)
		if p.Type.Nullable {
			// toDartType already appends ? for nullable types
			dartType := g.toDartType(p.Type)
			optional = append(optional, fmt.Sprintf("%s %s", dartType, paramName))
		} else {
			dartType := g.toDartType(p.Type)
			required = append(required, fmt.Sprintf("required %s %s", dartType, paramName))
		}
	}
	all := append(required, optional...)
	if len(all) == 0 {
		return ""
	}
	return "{" + strings.Join(all, ", ") + "}"
}

func (g *clientDartGen) methodReturnType(fn ast.Func) string {
	if fn.Return == nil {
		return "void"
	}
	return g.toDartType(*fn.Return)
}

func (g *clientDartGen) nonPathParams(fn ast.Func, pathParams []string) []ast.Param {
	pathSet := make(map[string]bool)
	for _, pp := range pathParams {
		pathSet[pp] = true
	}
	var result []ast.Param
	for _, p := range fn.Params {
		if !pathSet[p.Name] {
			result = append(result, p)
		}
	}
	return result
}

func (g *clientDartGen) toDartType(t ast.TypeRef) string {
	switch t.Kind {
	case ast.TypePrimitive:
		base := primitiveToDartType(t.Name)
		if t.Nullable {
			return base + "?"
		}
		return base
	case ast.TypeNamed:
		name := toPascalCase(t.Name)
		if t.Nullable {
			return name + "?"
		}
		return name
	case ast.TypeSlice:
		elem := g.toDartType(*t.Elem)
		return "List<" + elem + ">"
	case ast.TypeArray:
		elem := g.toDartType(*t.Elem)
		return "List<" + elem + ">"
	}
	return "dynamic"
}

func (g *clientDartGen) dartFromJson(t ast.TypeRef, expr string) string {
	if t.Nullable {
		inner := t
		inner.Nullable = false
		return fmt.Sprintf("%s == null ? null : %s", expr, g.dartFromJson(inner, expr))
	}
	switch t.Kind {
	case ast.TypePrimitive:
		switch t.Name {
		case "bool":
			return fmt.Sprintf("(%s as bool?) ?? false", expr)
		case "string":
			return fmt.Sprintf("(%s as String?) ?? ''", expr)
		case "f32", "f64":
			return fmt.Sprintf("(%s as num?)?.toDouble() ?? 0.0", expr)
		default:
			return fmt.Sprintf("(%s as num?)?.toInt() ?? 0", expr)
		}
	case ast.TypeNamed:
		className := toPascalCase(t.Name)
		// Check if it's an enum
		if g.isEnum(t.Name) {
			return fmt.Sprintf("%s.fromValue((%s as num?)?.toInt() ?? 0)", className, expr)
		}
		return fmt.Sprintf("%s.fromJson(%s as Map<String, dynamic>)", className, expr)
	case ast.TypeSlice:
		elemExpr := g.dartFromJson(*t.Elem, "e")
		return fmt.Sprintf("(%s as List? ?? []).map((e) => %s).toList()", expr, elemExpr)
	case ast.TypeArray:
		elemExpr := g.dartFromJson(*t.Elem, "e")
		return fmt.Sprintf("(%s as List? ?? []).map((e) => %s).toList()", expr, elemExpr)
	}
	return expr
}

func (g *clientDartGen) dartToJson(t ast.TypeRef, expr string) string {
	if t.Nullable {
		inner := t
		inner.Nullable = false
		return fmt.Sprintf("%s == null ? null : %s", expr, g.dartToJson(inner, expr+"!"))
	}
	switch t.Kind {
	case ast.TypePrimitive:
		return expr
	case ast.TypeNamed:
		if g.isEnum(t.Name) {
			return expr + ".value"
		}
		return expr + ".toJson()"
	case ast.TypeSlice, ast.TypeArray:
		elemExpr := g.dartToJson(*t.Elem, "e")
		if elemExpr == "e" {
			return expr
		}
		return fmt.Sprintf("%s.map((e) => %s).toList()", expr, elemExpr)
	}
	return expr
}

func (g *clientDartGen) isEnum(name string) bool {
	for _, e := range g.api.Enums {
		if e.Name == name {
			return true
		}
	}
	return false
}

func primitiveToDartType(name string) string {
	switch name {
	case "bool":
		return "bool"
	case "i8", "u8", "i32", "u32", "i64", "u64":
		return "int"
	case "f32", "f64":
		return "double"
	case "string":
		return "String"
	default:
		return "dynamic"
	}
}

// toDartConst converts UPPER_SNAKE to lowerCamelCase for top-level Dart constants.
// e.g. "MAX_CHANNELS" → "maxChannels"
func toDartConst(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// toDartEnumValue converts UPPER_SNAKE to lowerCamelCase for Dart enum values.
// e.g. "PRE_TRIG" → "preTrig"
func toDartEnumValue(s string) string {
	return toDartConst(s)
}

// toDartField converts snake_case to lowerCamelCase for Dart field names.
// e.g. "pin_name" → "pinName"
func toDartField(s string) string {
	parts := strings.Split(s, "_")
	for i := 1; i < len(parts); i++ {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	result := strings.Join(parts, "")
	return escapeDartKeyword(result)
}

// toDartMethod converts snake_case to lowerCamelCase for Dart method names.
func toDartMethod(s string) string {
	return toDartField(s)
}

// dartKeywords is the set of Dart reserved words.
var dartKeywords = map[string]bool{
	"abstract": true, "as": true, "assert": true, "async": true, "await": true,
	"break": true, "case": true, "catch": true, "class": true, "const": true,
	"continue": true, "covariant": true, "default": true, "deferred": true, "do": true,
	"dynamic": true, "else": true, "enum": true, "export": true, "extends": true,
	"extension": true, "external": true, "factory": true, "false": true, "final": true,
	"finally": true, "for": true, "Function": true, "get": true, "hide": true,
	"if": true, "implements": true, "import": true, "in": true, "interface": true,
	"is": true, "late": true, "library": true, "mixin": true, "new": true,
	"null": true, "of": true, "on": true, "operator": true, "part": true,
	"required": true, "rethrow": true, "return": true, "sealed": true, "set": true,
	"show": true, "static": true, "super": true, "switch": true, "sync": true,
	"this": true, "throw": true, "true": true, "try": true, "typedef": true,
	"var": true, "void": true, "when": true, "while": true, "with": true, "yield": true,
}

func escapeDartKeyword(name string) string {
	if dartKeywords[name] {
		return name + "_"
	}
	return name
}
