package cgen

import (
	"fmt"
	"io"
	"time"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GeneratePublishDrainHook writes a Go file that auto-starts a drain goroutine
// when the publish ring is registered in the API registry (via OnRegister).
// This file is compiled into the gomc-server binary via imports_generated.go
// so that the Go side automatically drains the ring without launcher knowledge.
//
// Returns false if the API has no @publish functions.
func GeneratePublishDrainHook(w io.Writer, api *ast.API, packageName string) (bool, error) {
	g := &publishDrainHookGen{w: w, api: api, pkg: packageName}
	if !g.hasPublishFuncs() {
		return false, nil
	}
	return true, g.generate()
}

type publishDrainHookGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *publishDrainHookGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *publishDrainHookGen) hasPublishFuncs() bool {
	for _, fn := range g.api.Funcs {
		if fn.Publish {
			return true
		}
	}
	return false
}

func (g *publishDrainHookGen) generate() error {
	g.printf("// Code generated by gmicompile - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)

	g.printf("import (\n")
	g.printf("\t\"sync\"\n")
	g.printf("\t\"time\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	// Suppress unused import warnings
	g.printf("var _ time.Duration\n")
	g.printf("var _ unsafe.Pointer\n\n")

	for _, fn := range g.api.Funcs {
		if !fn.Publish {
			continue
		}
		g.emitDrainHook(fn)
	}

	return g.err
}

func (g *publishDrainHookGen) emitDrainHook(fn ast.Func) {
	drainType := toPascalCase(fn.Name) + "Drain"
	apiRegName := fmt.Sprintf("%s_%s", g.api.Name, fn.Name)
	watchName := g.findWatchSourceName(fn.Name)

	// Default rate from the watch declaration (or 100ms fallback)
	defaultRate := 100 * time.Millisecond
	if watchName != "" {
		for _, wfn := range g.api.Funcs {
			if wfn.Name == watchName && wfn.WatchDefaultRate != "" {
				if parsed, err := time.ParseDuration(wfn.WatchDefaultRate); err == nil {
					defaultRate = parsed
				}
				break
			}
		}
	}
	rateMs := defaultRate.Milliseconds()

	g.printf("// --- Auto-drain hook for %s ---\n\n", fn.Name)

	// Package-level state for drain lifecycle (per-instance map)
	g.printf("var (\n")
	g.printf("\t%sDrainMu sync.Mutex\n", fn.Name)
	g.printf("\t%sDrains  map[string]*%s\n", fn.Name, drainType)
	g.printf(")\n\n")

	// init() subscribes to OnRegister
	g.printf("func init() {\n")
	g.printf("\tapiserver.OnDefaultRegistryReady(func(reg *apiserver.Registry) {\n")
	g.printf("\t\treg.OnRegister(func(api *apiserver.RegisteredAPI) {\n")
	g.printf("\t\t\tif api.APIName != %q {\n", apiRegName)
	g.printf("\t\t\t\treturn\n")
	g.printf("\t\t\t}\n")
	g.printf("\t\t\tstart%sDrain(api)\n", toPascalCase(fn.Name))
	g.printf("\t\t})\n")
	g.printf("\t})\n")
	g.printf("}\n\n")

	// startXxxDrain creates the drain, starts it, and registers WS watch
	g.printf("func start%sDrain(api *apiserver.RegisteredAPI) {\n", toPascalCase(fn.Name))
	g.printf("\t%sDrainMu.Lock()\n", fn.Name)
	g.printf("\tdefer %sDrainMu.Unlock()\n", fn.Name)
	g.printf("\n")
	g.printf("\tif %sDrains == nil {\n", fn.Name)
	g.printf("\t\t%sDrains = make(map[string]*%s)\n", fn.Name, drainType)
	g.printf("\t}\n\n")
	g.printf("\tinstance := api.Instance\n")
	g.printf("\tif _, exists := %sDrains[instance]; exists {\n", fn.Name)
	g.printf("\t\treturn // already started for this instance\n")
	g.printf("\t}\n\n")
	g.printf("\tdrain := New%s(api.Callbacks)\n", drainType)
	g.printf("\tdrain.Start()\n")
	g.printf("\t%sDrains[instance] = drain\n\n", fn.Name)

	// Register WS watch
	g.printf("\twreg := apiserver.DefaultWatchRegistry()\n")
	g.printf("\tif wreg == nil {\n")
	g.printf("\t\twreg = apiserver.NewWatchRegistry()\n")
	g.printf("\t\tapiserver.SetDefaultWatchRegistry(wreg)\n")
	g.printf("\t}\n")

	if watchName != "" {
		g.printf("\twreg.Register(&apiserver.WatchAPI{\n")
		g.printf("\t\tAPIName:  %q,\n", g.api.Name)
		g.printf("\t\tInstance: instance,\n")
		g.printf("\t\tWatches: []apiserver.WatchFuncMeta{\n")
		g.printf("\t\t\t{\n")
		g.printf("\t\t\t\tName:        %q,\n", watchName)
		g.printf("\t\t\t\tDefaultRate: %d * time.Millisecond,\n", rateMs)
		g.printf("\t\t\t\tWatch:       drain.WatchFunc(),\n")
		g.printf("\t\t\t},\n")
		g.printf("\t\t},\n")
		g.printf("\t})\n")
	}

	g.printf("}\n\n")

	// Stop function for a specific instance
	g.printf("// Stop%sDrain stops the drain for the given instance.\n", toPascalCase(fn.Name))
	g.printf("func Stop%sDrain(instance string) {\n", toPascalCase(fn.Name))
	g.printf("\t%sDrainMu.Lock()\n", fn.Name)
	g.printf("\tdefer %sDrainMu.Unlock()\n", fn.Name)
	g.printf("\tif %sDrains == nil {\n", fn.Name)
	g.printf("\t\treturn\n")
	g.printf("\t}\n")
	g.printf("\tif d, ok := %sDrains[instance]; ok {\n", fn.Name)
	g.printf("\t\td.Stop()\n")
	g.printf("\t\tdelete(%sDrains, instance)\n", fn.Name)
	g.printf("\t}\n")
	g.printf("}\n\n")

	// StopAll function for shutdown
	g.printf("// StopAll%sDrains stops all instance drains (called during shutdown).\n", toPascalCase(fn.Name))
	g.printf("func StopAll%sDrains() {\n", toPascalCase(fn.Name))
	g.printf("\t%sDrainMu.Lock()\n", fn.Name)
	g.printf("\tdefer %sDrainMu.Unlock()\n", fn.Name)
	g.printf("\tfor name, d := range %sDrains {\n", fn.Name)
	g.printf("\t\td.Stop()\n")
	g.printf("\t\tdelete(%sDrains, name)\n", fn.Name)
	g.printf("\t}\n")
	g.printf("}\n\n")
}

// findWatchSourceName finds the @watch function that sources from this publish func.
func (g *publishDrainHookGen) findWatchSourceName(publishName string) string {
	for _, fn := range g.api.Funcs {
		if fn.Watch && fn.WatchSource == publishName {
			return fn.Name
		}
	}
	return ""
}
