package cgen

import (
	"fmt"
	"io"
	"strings"

	"github.com/sittner/linuxcnc/src/gomc/internal/gmicompile/ast"
)

// GenerateServerWS writes Go code that creates WatchAPI registrations from
// the API's C callbacks. Watch functions and commands are extracted from the
// GMI function list based on @watch annotations.
func GenerateServerWS(w io.Writer, api *ast.API, packageName string) error {
	g := &serverWSGen{w: w, api: api, pkg: packageName}
	return g.generate()
}

// HasWatchFuncs returns true if any function in the API has @watch true.
func HasWatchFuncs(api *ast.API) bool {
	for _, fn := range api.Funcs {
		if fn.Watch {
			return true
		}
	}
	return false
}

type serverWSGen struct {
	w   io.Writer
	api *ast.API
	pkg string
	err error
}

func (g *serverWSGen) printf(format string, args ...interface{}) {
	if g.err != nil {
		return
	}
	_, g.err = fmt.Fprintf(g.w, format, args...)
}

func (g *serverWSGen) generate() error {
	g.emitHeader()
	g.emitWatchFuncs()
	g.emitCommandFuncs()
	g.emitRegisterWatch()
	return g.err
}

func (g *serverWSGen) emitHeader() {
	g.printf("// Code generated by gmicompile --server-ws - DO NOT EDIT.\n\n")
	g.printf("package %s\n\n", g.pkg)

	g.printf("import (\n")
	g.printf("\t\"encoding/json\"\n")
	g.printf("\t\"time\"\n")
	g.printf("\t\"unsafe\"\n")
	g.printf("\n")
	g.printf("\t\"github.com/sittner/linuxcnc/src/gomc/internal/apiserver\"\n")
	g.printf(")\n\n")

	g.printf("var _ = json.Marshal\n")
	g.printf("var _ = time.Second\n")
	g.printf("var _ unsafe.Pointer\n\n")
}

// watchFuncs returns functions annotated with @watch true.
func (g *serverWSGen) watchFuncs() []ast.Func {
	var fns []ast.Func
	for _, fn := range g.api.Funcs {
		if fn.Watch {
			fns = append(fns, fn)
		}
	}
	return fns
}

// commandFuncs returns functions NOT annotated with @watch (non-void, callable commands).
func (g *serverWSGen) commandFuncs() []ast.Func {
	var fns []ast.Func
	for _, fn := range g.api.Funcs {
		if !fn.Watch {
			fns = append(fns, fn)
		}
	}
	return fns
}

func (g *serverWSGen) emitWatchFuncs() {
	watches := g.watchFuncs()
	if len(watches) == 0 {
		return
	}

	g.printf("// --- Watch function wrappers ---\n\n")

	for _, fn := range watches {
		goName := toPascalCase(fn.Name)

		// Each watch function is a closure over the callbacks pointer
		// that calls the dispatch function and returns JSON.
		g.printf("// makeWatch%s creates a WatchFunc that calls %s on the callbacks.\n", goName, fn.Name)
		g.printf("func makeWatch%s(callbacks unsafe.Pointer) apiserver.WatchFunc {\n", goName)
		g.printf("\treturn func() (json.RawMessage, error) {\n")

		// Call the dispatch function (which is already generated by --server-go)
		g.printf("\t\tresult, err := %sDispatch%s(callbacks, nil)\n", g.api.Name, goName)
		g.printf("\t\tif err != nil {\n")
		g.printf("\t\t\treturn nil, err\n")
		g.printf("\t\t}\n")
		g.printf("\t\treturn json.RawMessage(result), nil\n")
		g.printf("\t}\n")
		g.printf("}\n\n")
	}
}

func (g *serverWSGen) emitCommandFuncs() {
	commands := g.commandFuncs()
	if len(commands) == 0 {
		return
	}

	g.printf("// --- Command function wrappers ---\n\n")

	for _, fn := range commands {
		goName := toPascalCase(fn.Name)

		g.printf("// makeCommand%s creates a CommandFunc that calls %s on the callbacks.\n", goName, fn.Name)
		g.printf("func makeCommand%s(callbacks unsafe.Pointer) apiserver.CommandFunc {\n", goName)
		g.printf("\treturn func(req json.RawMessage) (json.RawMessage, error) {\n")
		g.printf("\t\tresult, err := %sDispatch%s(callbacks, []byte(req))\n", g.api.Name, goName)
		g.printf("\t\tif err != nil {\n")
		g.printf("\t\t\treturn nil, err\n")
		g.printf("\t\t}\n")
		g.printf("\t\treturn json.RawMessage(result), nil\n")
		g.printf("\t}\n")
		g.printf("}\n\n")
	}
}

func (g *serverWSGen) emitRegisterWatch() {
	watches := g.watchFuncs()
	commands := g.commandFuncs()

	g.printf("// --- Watch registration ---\n\n")
	g.printf("// NewWatchAPI creates a WatchAPI for the %s API from registered callbacks.\n", g.api.Name)
	g.printf("func NewWatchAPI(instance string, callbacks unsafe.Pointer) *apiserver.WatchAPI {\n")
	g.printf("\treturn &apiserver.WatchAPI{\n")
	g.printf("\t\tAPIName:  %q,\n", g.api.Name)
	g.printf("\t\tInstance: instance,\n")

	// Watches
	g.printf("\t\tWatches: []apiserver.WatchFuncMeta{\n")
	for _, fn := range watches {
		goName := toPascalCase(fn.Name)
		rate := "100 * time.Millisecond" // default
		if fn.WatchDefaultRate != "" {
			rate = parseRateLiteral(fn.WatchDefaultRate)
		}
		g.printf("\t\t\t{\n")
		g.printf("\t\t\t\tName:        %q,\n", fn.Name)
		g.printf("\t\t\t\tDefaultRate: %s,\n", rate)
		g.printf("\t\t\t\tWatch:       makeWatch%s(callbacks),\n", goName)
		g.printf("\t\t\t},\n")
	}
	g.printf("\t\t},\n")

	// Commands
	g.printf("\t\tCommands: []apiserver.CommandMeta{\n")
	for _, fn := range commands {
		goName := toPascalCase(fn.Name)
		g.printf("\t\t\t{\n")
		g.printf("\t\t\t\tName:    %q,\n", fn.Name)
		g.printf("\t\t\t\tHandler: makeCommand%s(callbacks),\n", goName)
		g.printf("\t\t\t},\n")
	}
	g.printf("\t\t},\n")

	g.printf("\t}\n")
	g.printf("}\n")

	// Emit init() to register the watch factory so gomc_api_register_cb
	// can create WatchAPIs without knowing the concrete generated types.
	g.printf("\nfunc init() {\n")
	g.printf("\tapiserver.RegisterWatchFactory(%q, NewWatchAPI)\n", g.api.Name)
	g.printf("}\n")
}

// parseRateLiteral converts "50ms", "1s", etc. to a Go time.Duration literal.
func parseRateLiteral(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasSuffix(s, "ms") {
		num := strings.TrimSuffix(s, "ms")
		return fmt.Sprintf("%s * time.Millisecond", num)
	}
	if strings.HasSuffix(s, "s") {
		num := strings.TrimSuffix(s, "s")
		return fmt.Sprintf("%s * time.Second", num)
	}
	// Default: treat as milliseconds
	return fmt.Sprintf("%s * time.Millisecond", s)
}
